const dataBarang = [
  { no: 1, namaBarang: "Absen", typeUkuranWarna: "-", merk: "-", hargaEcer: 4000, hargaPack: null },
  { no: 2, namaBarang: "Binder", typeUkuranWarna: "Looseleaf/A5", merk: "-", hargaEcer: 24000, hargaPack: null },
  { no: 3, namaBarang: "Binder", typeUkuranWarna: "The Coil/A6", merk: "-", hargaEcer: 13000, hargaPack: null },
  { no: 4, namaBarang: "Binder", typeUkuranWarna: "E-156/Erica", merk: "-", hargaEcer: 6000, hargaPack: null },
  { no: 5, namaBarang: "Binder", typeUkuranWarna: "Diary Fashion", merk: "-", hargaEcer: 23000, hargaPack: null },
  { no: 6, namaBarang: "Binder", typeUkuranWarna: "Wengu", merk: "-", hargaEcer: 16000, hargaPack: null },
  { no: 7, namaBarang: "Binder", typeUkuranWarna: "Ajp Mart", merk: "-", hargaEcer: 20000, hargaPack: null },
  { no: 8, namaBarang: "Binder", typeUkuranWarna: "Np-404/Batik", merk: "-", hargaEcer: 6500, hargaPack: null },
  { no: 9, namaBarang: "Buku Akuntansi", typeUkuranWarna: "Isi 50/F4", merk: "-", hargaEcer: 14000, hargaPack: null },
  { no: 10, namaBarang: "Buku Akuntansi", typeUkuranWarna: "Isi 100/F4", merk: "-", hargaEcer: 18000, hargaPack: null },
  { no: 11, namaBarang: "Buku Akuntansi", typeUkuranWarna: "Kwarto", merk: "-", hargaEcer: 12000, hargaPack: null },
  { no: 12, namaBarang: "Buku Akuntansi", typeUkuranWarna: "A6", merk: "-", hargaEcer: 7000, hargaPack: null },
  { no: 13, namaBarang: "Buku Gambar", typeUkuranWarna: "A4", merk: "Sidu, dll.", hargaEcer: 4000, hargaPack: null },
  { no: 14, namaBarang: "Buku Gambar", typeUkuranWarna: "A3", merk: "Sidu, dll.", hargaEcer: 8000, hargaPack: null },
  { no: 15, namaBarang: "Buku Kas", typeUkuranWarna: "Kecil", merk: "-", hargaEcer: 10000, hargaPack: null },
  { no: 16, namaBarang: "Buku Kas", typeUkuranWarna: "Besar", merk: "-", hargaEcer: 15000, hargaPack: null },
  { no: 17, namaBarang: "Buku Panjang", typeUkuranWarna: "Hard Cover/Folio", merk: "-", hargaEcer: 12000, hargaPack: null },
  { no: 18, namaBarang: "Buku Tulis", typeUkuranWarna: "Isi 38/Kecil", merk: "Sidu / Vision", hargaEcer: 5000, hargaPack: 35000 },
  { no: 19, namaBarang: "Buku Tulis", typeUkuranWarna: "Isi 58/Kecil", merk: "Sidu", hargaEcer: 5500, hargaPack: null },
  { no: 20, namaBarang: "Buku Tulis", typeUkuranWarna: "Kotak Kecil", merk: "-", hargaEcer: 5000, hargaPack: null },
  { no: 21, namaBarang: "Buku Tulis", typeUkuranWarna: "Halus", merk: "-", hargaEcer: 5000, hargaPack: null },
  { no: 22, namaBarang: "Buku Tulis", typeUkuranWarna: "Isi 36/Besar", merk: "Big Boss", hargaEcer: 6000, hargaPack: 48000 },
  { no: 23, namaBarang: "Buku Tulis", typeUkuranWarna: "Isi 42/Besar", merk: "Big Boss", hargaEcer: 6500, hargaPack: 36000 },
  { no: 24, namaBarang: "Buku Tulis", typeUkuranWarna: "Kotak/10mm", merk: "-", hargaEcer: 5000, hargaPack: null },
  { no: 25, namaBarang: "Buku Tulis", typeUkuranWarna: "Kotak/14mm", merk: "-", hargaEcer: 5000, hargaPack: null },
  { no: 26, namaBarang: "Kwitansi", typeUkuranWarna: "Kecil", merk: "-", hargaEcer: 4000, hargaPack: null },
  { no: 27, namaBarang: "Kwitansi", typeUkuranWarna: "Besar", merk: "-", hargaEcer: 5500, hargaPack: null },
  { no: 28, namaBarang: "Milimeter Block", typeUkuranWarna: "-", merk: "-", hargaEcer: 6000, hargaPack: null },
  { no: 29, namaBarang: "Nota", typeUkuranWarna: "1ply/Kecil", merk: "-", hargaEcer: 3000, hargaPack: null },
  { no: 30, namaBarang: "Nota", typeUkuranWarna: "2ply/Kecil", merk: "-", hargaEcer: 4000, hargaPack: null },
  { no: 31, namaBarang: "Nota", typeUkuranWarna: "1ply/Kecil", merk: "-", hargaEcer: 6000, hargaPack: null },
  { no: 32, namaBarang: "Pepak", typeUkuranWarna: "-", merk: "-", hargaEcer: 15000, hargaPack: null },
  { no: 33, namaBarang: "Tabungan", typeUkuranWarna: "-", merk: "-", hargaEcer: 2000, hargaPack: null }
];