const dataBarang = [
  { no: 1, kategori: "Scan", ukuran: "A4", harga: 1000, ket: null },
  { no: 2, kategori: "Scan", ukuran: "F4", harga: 1500, ket: null },
  { no: 3, kategori: "Kirim File/Save File", ukuran: "A4/F4", harga: 1000, ket: null },
  { no: 4, kategori: "Laminating", ukuran: "KTP", harga: 2000, ket: null },
  { no: 5, kategori: "Laminating", ukuran: "A4/F4", harga: 5000, ket: null },
  { no: 6, kategori: "Laminating", ukuran: "A3", harga: 10000, ket: null },
  { no: 7, kategori: "Press Mika", ukuran: "-", harga: 3000, ket: null },
  { no: 8, kategori: "Laminasi", ukuran: "-", harga: 3000, ket: null },
  { no: 9, kategori: "Edit", ukuran: "Mudah", harga: 2000, ket: null },
  { no: 10, kategori: "Edit", ukuran: "Sedang", harga: 3000, ket: null },
  { no: 11, kategori: "Edit", ukuran: "Sulit", harga: 5000, ket: null },
  { no: 12, kategori: "Pengetikan", ukuran: "A4", harga: 5000, ket: null },
  { no: 13, kategori: "Pengetikan", ukuran: "F4", harga: 7000, ket: null },
  { no: 14, kategori: "Pengetikan Express", ukuran: "A4", harga: 7000, ket: "Kondisional" },
  { no: 15, kategori: "Pengetikan Express", ukuran: "F4", harga: 9000, ket: "Kondisional" },
  { no: 16, kategori: "Jilid Spiral", ukuran: "Kecil", harga: 7000, ket: null },
  { no: 17, kategori: "Jilid Spiral", ukuran: "Sedang", harga: 10000, ket: null },
  { no: 18, kategori: "Jilid Spiral", ukuran: "Besar", harga: 15000, ket: null },
  { no: 19, kategori: "Jilid Regular", ukuran: "A4/F4", harga: 3000, ket: "Staples + Lakban" },
  { no: 20, kategori: "Jilid Premium", ukuran: "A4/F4", harga: 5000, ket: "Mika + Buffallo" },
  { no: 21, kategori: "Jilid Soft Cover", ukuran: "-", harga: 25000, ket: "Proses 1-2 Hari" },
  { no: 22, kategori: "Jilid Hard Cover", ukuran: "-", harga: 35000, ket: "Proses 1-2 Hari" },
  { no: 23, kategori: "Id card/custom", ukuran: "-", harga: 10000, ket: "Belum termasuk Desain" },
  { no: 24, kategori: "Name Tag", ukuran: "Biasa", harga: 7000, ket: "Custom" },
  { no: 25, kategori: "Name Tag", ukuran: "Resin/Kemiti", harga: 20000, ket: null },
  { no: 26, kategori: "Name Tag", ukuran: "Magnet", harga: 35000, ket: null },
  { no: 27, kategori: "Stempel Kayu", ukuran: "Semua Ukuran", harga: 50000, ket: "desain tidak sulit" },
  { no: 28, kategori: "Stempel Flash", ukuran: "Pricelist + 20.000", harga: null, ket: "Free Desain, desain tidak sulit" },
  { no: 29, kategori: "Stempel Flash", ukuran: "Ada Desain", harga: -5000, ket: "Potongan harga jika sudah ada desain" }
];