const dataBarang = [
  { no: 1, namaBarang: "Baterai", typeUkuranWarna: "AA", merk: "Alkaline", hargaEcer: 6000, hargaPack: null },
  { no: 2, namaBarang: "Baterai", typeUkuranWarna: "AAA", merk: "Alkaline", hargaEcer: 7000, hargaPack: null },
  { no: 3, namaBarang: "Baterai", typeUkuranWarna: "AA", merk: "ABC", hargaEcer: 3000, hargaPack: null },
  { no: 4, namaBarang: "Benang Jahit", typeUkuranWarna: "-", merk: "Butterfly", hargaEcer: 2000, hargaPack: null },
  { no: 5, namaBarang: "Benang Woll", typeUkuranWarna: "-", merk: "-", hargaEcer: 10000, hargaPack: null },
  { no: 6, namaBarang: "Bendera", typeUkuranWarna: "Merah Putih", merk: "-", hargaEcer: 1000, hargaPack: null },
  { no: 7, namaBarang: "Cermin", typeUkuranWarna: "-", merk: "-", hargaEcer: 3000, hargaPack: null },
  { no: 8, namaBarang: "Clay", typeUkuranWarna: "Kecil", merk: "-", hargaEcer: 6000, hargaPack: null },
  { no: 9, namaBarang: "Clay", typeUkuranWarna: "Besar", merk: "-", hargaEcer: 9000, hargaPack: null },
  { no: 10, namaBarang: "Corrugated Paper", typeUkuranWarna: "-", merk: "Kokoro", hargaEcer: 15000, hargaPack: null },
  { no: 11, namaBarang: "Cotton Bud", typeUkuranWarna: "-", merk: "All", hargaEcer: 2000, hargaPack: null },
  { no: 12, namaBarang: "Gantungan Kunci", typeUkuranWarna: "Kecil", merk: "-", hargaEcer: 2000, hargaPack: null },
  { no: 13, namaBarang: "Gantungan Kunci", typeUkuranWarna: "Tali Tanpa Inisial", merk: "-", hargaEcer: 8000, hargaPack: null },
  { no: 14, namaBarang: "Gantungan Kunci", typeUkuranWarna: "Tali + Inisial", merk: "-", hargaEcer: 9000, hargaPack: null },
  { no: 15, namaBarang: "Gantungan Kunci", typeUkuranWarna: "Boneka Karet", merk: "-", hargaEcer: 8000, hargaPack: null },
  { no: 16, namaBarang: "Gantungan Kunci", typeUkuranWarna: "Panda", merk: "-", hargaEcer: 9000, hargaPack: null },
  { no: 17, namaBarang: "Glitter", typeUkuranWarna: "-", merk: "-", hargaEcer: 4000, hargaPack: null },
  { no: 18, namaBarang: "Gunting kuku", typeUkuranWarna: "Kecil", merk: "-", hargaEcer: 4000, hargaPack: null },
  { no: 19, namaBarang: "Gunting kuku", typeUkuranWarna: "Besar", merk: "-", hargaEcer: 8000, hargaPack: null },
  { no: 20, namaBarang: "Id Card", typeUkuranWarna: "Klip Kartu Plastik", merk: "-", hargaEcer: 2000, hargaPack: null },
  { no: 21, namaBarang: "Id Card", typeUkuranWarna: "Klip Kartu Besi", merk: "-", hargaEcer: 2000, hargaPack: null },
  { no: 22, namaBarang: "Id Card", typeUkuranWarna: "Yoyo/Warna Warni", merk: "-", hargaEcer: 4000, hargaPack: null },
  { no: 23, namaBarang: "Id Card", typeUkuranWarna: "Holder + Tali/54x85mm", merk: "-", hargaEcer: 4500, hargaPack: null },
  { no: 24, namaBarang: "Id Card", typeUkuranWarna: "Plastik/A1", merk: "BIG", hargaEcer: 2000, hargaPack: 15000 },
  { no: 25, namaBarang: "Id Card", typeUkuranWarna: "Plastik/A2", merk: "BIG", hargaEcer: 2000, hargaPack: 16000 },
  { no: 26, namaBarang: "Id Card", typeUkuranWarna: "Plastik/A3", merk: "BIG", hargaEcer: 2000, hargaPack: 18000 },
  { no: 27, namaBarang: "Id Card", typeUkuranWarna: "Plastik/B1", merk: "BIG", hargaEcer: 2000, hargaPack: 15000 },
  { no: 28, namaBarang: "Id Card", typeUkuranWarna: "Plastik/B2", merk: "BIG", hargaEcer: 2000, hargaPack: 17000 },
  { no: 29, namaBarang: "Id Card", typeUkuranWarna: "Plastik/B3", merk: "BIG", hargaEcer: 2000, hargaPack: 18000 },
  { no: 30, namaBarang: "Id Card", typeUkuranWarna: "Plastik/B4", merk: "BIG", hargaEcer: 2500, hargaPack: 23000 },
  { no: 31, namaBarang: "Id Card", typeUkuranWarna: "Holder Plastik/Satuan", merk: "-", hargaEcer: 2500, hargaPack: null },
  { no: 32, namaBarang: "Id Card", typeUkuranWarna: "Tali Keplek/Kecil", merk: "-", hargaEcer: 2000, hargaPack: null },
  { no: 33, namaBarang: "Id Card", typeUkuranWarna: "Tali Keplek/Besar", merk: "-", hargaEcer: 4500, hargaPack: null },
  { no: 34, namaBarang: "Jarum Jahit", typeUkuranWarna: "-", merk: "-", hargaEcer: 3500, hargaPack: null },
  { no: 35, namaBarang: "Jarum Pentul", typeUkuranWarna: "Kecil", merk: "-", hargaEcer: 2000, hargaPack: null },
  { no: 36, namaBarang: "Jarum Pentul", typeUkuranWarna: "Besar", merk: "-", hargaEcer: 3000, hargaPack: null },
  { no: 37, namaBarang: "Jepit Rambut", typeUkuranWarna: "Motif", merk: "-", hargaEcer: 7500, hargaPack: null },
  { no: 38, namaBarang: "Jepit Rambut", typeUkuranWarna: "Polos", merk: "-", hargaEcer: 2000, hargaPack: null },
  { no: 39, namaBarang: "Kabel", typeUkuranWarna: "Type C", merk: "Veger", hargaEcer: 20000, hargaPack: null },
  { no: 40, namaBarang: "Kabel", typeUkuranWarna: "Micro", merk: "Veger", hargaEcer: 15000, hargaPack: null },
  { no: 41, namaBarang: "Kabel", typeUkuranWarna: "Lightning", merk: "Veger", hargaEcer: 20000, hargaPack: null },
  { no: 42, namaBarang: "Kabel", typeUkuranWarna: "Headphone/Headset", merk: "U Music 19", hargaEcer: 10000, hargaPack: null },
  { no: 43, namaBarang: "Kain Flanel", typeUkuranWarna: "-", merk: "-", hargaEcer: 2500, hargaPack: null },
  { no: 44, namaBarang: "Kanvas", typeUkuranWarna: "20x30cm", merk: "-", hargaEcer: 12000, hargaPack: null },
  { no: 45, namaBarang: "Kanvas", typeUkuranWarna: "30x30cm", merk: "-", hargaEcer: 15000, hargaPack: null },
  { no: 46, namaBarang: "Kanvas", typeUkuranWarna: "30x40cm", merk: "-", hargaEcer: 18000, hargaPack: null },
  { no: 47, namaBarang: "Kawat Bulu", typeUkuranWarna: "-", merk: "-", hargaEcer: 1000, hargaPack: null },
  { no: 48, namaBarang: "Lilin", typeUkuranWarna: "Putih", merk: "-", hargaEcer: 2000, hargaPack: null },
  { no: 49, namaBarang: "Lilin Ulang Tahun", typeUkuranWarna: "Spiral/Kecil", merk: "-", hargaEcer: 4000, hargaPack: null },
  { no: 50, namaBarang: "Masker", typeUkuranWarna: "-", merk: "-", hargaEcer: 2000, hargaPack: null },
  { no: 51, namaBarang: "Paper Bag", typeUkuranWarna: "Kecil (Coklat)", merk: "-", hargaEcer: 3000, hargaPack: null },
  { no: 52, namaBarang: "Paper Bag", typeUkuranWarna: "Sedang", merk: "-", hargaEcer: 7500, hargaPack: null },
  { no: 53, namaBarang: "Paper Bag", typeUkuranWarna: "Sedang Corak", merk: "-", hargaEcer: 12000, hargaPack: null },
  { no: 54, namaBarang: "Paper Bag", typeUkuranWarna: "Besar", merk: "-", hargaEcer: 8000, hargaPack: null },
  { no: 55, namaBarang: "Paper Bag", typeUkuranWarna: "Extra Besar", merk: "-", hargaEcer: 10000, hargaPack: null },
  { no: 56, namaBarang: "Pencukur Kumis", typeUkuranWarna: "Biru", merk: "Gillette", hargaEcer: 10000, hargaPack: null },
  { no: 57, namaBarang: "Pencukur Kumis", typeUkuranWarna: "Kuning", merk: "Gillette", hargaEcer: 7000, hargaPack: null },
  { no: 58, namaBarang: "Peniti", typeUkuranWarna: "Besar", merk: "-", hargaEcer: 7000, hargaPack: null },
  { no: 59, namaBarang: "Peniti", typeUkuranWarna: "Orlet Kuning/Putih", merk: "-", hargaEcer: 1000, hargaPack: null },
  { no: 60, namaBarang: "Peniti", typeUkuranWarna: "Biting Swam 12pcs", merk: "-", hargaEcer: 2000, hargaPack: null },
  { no: 61, namaBarang: "Peniti", typeUkuranWarna: "Bros", merk: "-", hargaEcer: 1000, hargaPack: null },
  { no: 62, namaBarang: "Pinset", typeUkuranWarna: "-", merk: "-", hargaEcer: 3000, hargaPack: null },
  { no: 63, namaBarang: "Pita Pull Bow Ribbon", typeUkuranWarna: "-", merk: "-", hargaEcer: 2000, hargaPack: null },
  { no: 64, namaBarang: "Pita Satin", typeUkuranWarna: "0,5cm/Meter", merk: "-", hargaEcer: 2000, hargaPack: null },
  { no: 65, namaBarang: "Pita Satin", typeUkuranWarna: "1,5cm", merk: "-", hargaEcer: 6500, hargaPack: null },
  { no: 66, namaBarang: "Pita Satin", typeUkuranWarna: "2,5cm", merk: "-", hargaEcer: 10000, hargaPack: null },
  { no: 67, namaBarang: "Pita Satin", typeUkuranWarna: "2cm", merk: "-", hargaEcer: 9000, hargaPack: null },
  { no: 68, namaBarang: "Pita Satin", typeUkuranWarna: "Merah Putih", merk: "-", hargaEcer: 9000, hargaPack: null },
  { no: 69, namaBarang: "Plastik", typeUkuranWarna: "STNK", merk: "-", hargaEcer: 2000, hargaPack: null },
  { no: 70, namaBarang: "Plastik", typeUkuranWarna: "KTP", merk: "-", hargaEcer: 1000, hargaPack: null },
  { no: 71, namaBarang: "Plastik", typeUkuranWarna: "Press Mika/A4", merk: "-", hargaEcer: 2000, hargaPack: null },
  { no: 72, namaBarang: "Plastisin/Malam", typeUkuranWarna: "Kecil", merk: "-", hargaEcer: 3000, hargaPack: null },
  { no: 73, namaBarang: "Plastisin/Malam", typeUkuranWarna: "Besar", merk: "-", hargaEcer: 8000, hargaPack: null },
  { no: 74, namaBarang: "Rumbai", typeUkuranWarna: "Kecil", merk: "All", hargaEcer: 3000, hargaPack: null },
  { no: 75, namaBarang: "Rumbai", typeUkuranWarna: "Besar", merk: "All", hargaEcer: 10000, hargaPack: null },
  { no: 76, namaBarang: "Sarung Tangan", typeUkuranWarna: "-", merk: "All", hargaEcer: 8500, hargaPack: null },
  { no: 77, namaBarang: "Stick Ice Cream", typeUkuranWarna: "Polos", merk: "-", hargaEcer: 2000, hargaPack: null },
  { no: 78, namaBarang: "Stick Ice Cream", typeUkuranWarna: "Warna", merk: "-", hargaEcer: 4000, hargaPack: null },
  { no: 79, namaBarang: "Sticker Dinding", typeUkuranWarna: "-", merk: "-", hargaEcer: 12000, hargaPack: null },
  { no: 80, namaBarang: "Sticker Label", typeUkuranWarna: "-", merk: "-", hargaEcer: 9000, hargaPack: null },
  { no: 81, namaBarang: "Strip Masker", typeUkuranWarna: "Tali", merk: "madebymi", hargaEcer: 6000, hargaPack: null },
  { no: 82, namaBarang: "Strip Masker", typeUkuranWarna: "Manik Manik", merk: "madebymi", hargaEcer: 13000, hargaPack: null },
  { no: 83, namaBarang: "Strip Masker", typeUkuranWarna: "Tali", merk: "No Merk", hargaEcer: 7000, hargaPack: null },
  { no: 84, namaBarang: "Tali Rambut", typeUkuranWarna: "Polos", merk: "-", hargaEcer: 2000, hargaPack: null },
  { no: 85, namaBarang: "Tali Rambut", typeUkuranWarna: "Motif", merk: "-", hargaEcer: 7000, hargaPack: null },
  { no: 86, namaBarang: "Tirai Dekorasi Pesta", typeUkuranWarna: "-", merk: "Vis-1", hargaEcer: 16000, hargaPack: null },
  { no: 87, namaBarang: "Tisu", typeUkuranWarna: "Basah", merk: "-", hargaEcer: 2000, hargaPack: null },
  { no: 88, namaBarang: "Tisu", typeUkuranWarna: "Kering/Kecil", merk: "-", hargaEcer: 2000, hargaPack: null },
  { no: 89, namaBarang: "Tisu", typeUkuranWarna: "Kering/Besar", merk: "-", hargaEcer: 6000, hargaPack: null },
  { no: 90, namaBarang: "Twist Tie", typeUkuranWarna: "-", merk: "-", hargaEcer: 5000, hargaPack: null },
  { no: 91, namaBarang: "Uno", typeUkuranWarna: "-", merk: "-", hargaEcer: 12500, hargaPack: null },
  { no: 92, namaBarang: "Wash Bag", typeUkuranWarna: "Kecil", merk: "-", hargaEcer: 5000, hargaPack: null },
  { no: 93, namaBarang: "Wash Bag", typeUkuranWarna: "Besar", merk: "-", hargaEcer: 5500, hargaPack: null }
];