const dataBarang = [
    { nama: "Bak Stempel", tipe: "Kecil", ukuran: "-", merk: "Joyko", hargaEcer: "7.000", hargaPack: "-", keterangan: "-" },
    { nama: "Bak Stempel", tipe: "Besar", ukuran: "-", merk: "Hero", hargaEcer: "9.000", hargaPack: "-", keterangan: "-" },
    { nama: "Busur", tipe: "-", ukuran: "-", merk: "No Merk", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Busur", tipe: "-", ukuran: "-", merk: "Butterfly", hargaEcer: "4.500", hargaPack: "-", keterangan: "-" },
    { nama: "Cat", tipe: "Warna/Kecil", ukuran: "-", merk: "Aga", hargaEcer: "10.000", hargaPack: "-", keterangan: "-" },
    { nama: "Cat", tipe: "Warna/Besar", ukuran: "-", merk: "Aga", hargaEcer: "18.000", hargaPack: "-", keterangan: "-" },
    { nama: "Cat", tipe: "Acrylic/12 Shades", ukuran: "-", merk: "Morning Star", hargaEcer: "16.000", hargaPack: "-", keterangan: "-" },
    { nama: "Cat", tipe: "Air", ukuran: "-", merk: "Mr.Loveguitar", hargaEcer: "12.000", hargaPack: "-", keterangan: "-" },
    { nama: "CorrectionTape (Stipo)", tipe: "Fluid(Cair)", ukuran: "-", merk: "Joyko", hargaEcer: "5.000", hargaPack: "-", keterangan: "-" },
    { nama: "CorrectionTape (Stipo)", tipe: "Fluid(Cair)", ukuran: "-", merk: "Grebeell", hargaEcer: "6.000", hargaPack: "-", keterangan: "-" },
    { nama: "CorrectionTape (Stipo)", tipe: "Kertas", ukuran: "-", merk: "Joyko", hargaEcer: "7.000", hargaPack: "-", keterangan: "-" },
    { nama: "CorrectionTape (Stipo)", tipe: "Kertas", ukuran: "-", merk: "Jenia, dll.", hargaEcer: "6.000", hargaPack: "-", keterangan: "-" },
    { nama: "Cutter", tipe: "Mini", ukuran: "-", merk: "-", hargaEcer: "4.000", hargaPack: "-", keterangan: "-" },
    { nama: "Cutter", tipe: "Kecil", ukuran: "-", merk: "Kenko", hargaEcer: "7.500", hargaPack: "-", keterangan: "-" },
    { nama: "Cutter", tipe: "Besar", ukuran: "-", merk: "Kenko", hargaEcer: "14.000", hargaPack: "-", keterangan: "-" },
    { nama: "Cutter", tipe: "Kecil", ukuran: "-", merk: "Safari", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Cutter", tipe: "Besar", ukuran: "-", merk: "Safari", hargaEcer: "6.000", hargaPack: "-", keterangan: "-" },
    { nama: "Double Tape", tipe: "Foam/Besar", ukuran: "-", merk: "Berry Tape", hargaEcer: "9.000", hargaPack: "-", keterangan: "-" },
    { nama: "Double Tape", tipe: "Foam/Kecil", ukuran: "-", merk: "NachiTape, dll.", hargaEcer: "6.000", hargaPack: "-", keterangan: "-" },
    { nama: "Double Tape", tipe: "Kecil", ukuran: "-", merk: "NachiTape, dll.", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Double Tape", tipe: "12mm", ukuran: "-", merk: "NachiTape, dll.", hargaEcer: "4.000", hargaPack: "-", keterangan: "-" },
    { nama: "Double Tape", tipe: "Akrilik", ukuran: "-", merk: "Trifelo", hargaEcer: "8.000", hargaPack: "-", keterangan: "-" },
    { nama: "Double Tape", tipe: "Besar", ukuran: "-", merk: "NachiTape, dll.", hargaEcer: "12.000", hargaPack: "-", keterangan: "-" },
    { nama: "Double Tape", tipe: "Sedang", ukuran: "-", merk: "NachiTape, dll.", hargaEcer: "6.500", hargaPack: "-", keterangan: "-" },
    { nama: "Gabus/Sterofoam", tipe: "Polos", ukuran: "-", merk: "-", hargaEcer: "8.000", hargaPack: "-", keterangan: "-" },
    { nama: "Gabus/Sterofoam", tipe: "Warna", ukuran: "-", merk: "-", hargaEcer: "10.000", hargaPack: "-", keterangan: "-" },
    { nama: "Gunting", tipe: "Kecil", ukuran: "-", merk: "Kenko", hargaEcer: "5.500", hargaPack: "-", keterangan: "-" },
    { nama: "Gunting", tipe: "Sedang", ukuran: "-", merk: "Kenko", hargaEcer: "8.000", hargaPack: "-", keterangan: "-" },
    { nama: "Gunting", tipe: "Besar", ukuran: "-", merk: "Kenko", hargaEcer: "12.000", hargaPack: "-", keterangan: "-" },
    { nama: "Gunting", tipe: "Kecil", ukuran: "-", merk: "Orlee/dsb.", hargaEcer: "5.000", hargaPack: "-", keterangan: "-" },
    { nama: "Gunting", tipe: "Sedang", ukuran: "-", merk: "Orlee/dsb.", hargaEcer: "6.000", hargaPack: "-", keterangan: "-" },
    { nama: "Gunting", tipe: "Besar", ukuran: "-", merk: "Orlee/dsb.", hargaEcer: "8.000", hargaPack: "-", keterangan: "-" },
    { nama: "Isi Cutter", tipe: "Kecil", ukuran: "-", merk: "Kenko", hargaEcer: "5.000", hargaPack: "-", keterangan: "-" },
    { nama: "Isi Cutter", tipe: "Besar", ukuran: "-", merk: "Kenko", hargaEcer: "6.000", hargaPack: "-", keterangan: "-" },
    { nama: "Isi Lem Tembak", tipe: "-", ukuran: "-", merk: "-", hargaEcer: "1.500", hargaPack: "-", keterangan: "-" },
    { nama: "Isi Staples", tipe: "5mm/kecil", ukuran: "-", merk: "Max", hargaEcer: "4.000", hargaPack: "-", keterangan: "-" },
    { nama: "Isi Staples", tipe: "24/6", ukuran: "-", merk: "Etona", hargaEcer: "7.000", hargaPack: "-", keterangan: "-" },
    { nama: "Isi Staples", tipe: "23/15", ukuran: "-", merk: "Etona", hargaEcer: "21.000", hargaPack: "-", keterangan: "-" },
    { nama: "Isi Staples", tipe: "23/13", ukuran: "-", merk: "Etona", hargaEcer: "18.000", hargaPack: "-", keterangan: "-" },
    { nama: "Isi Staples", tipe: "23/8", presidential: "-", ukuran: "-", merk: "Etona", hargaEcer: "10.000", hargaPack: "-", keterangan: "-" },
    { nama: "Isi Staples", tipe: "23/10", ukuran: "-", merk: "Etona", hargaEcer: "15.000", hargaPack: "-", keterangan: "-" },
    { nama: "Isolasi", tipe: "12mm/Kecil", ukuran: "-", merk: "Borneo", hargaEcer: "2.500", hargaPack: "-", keterangan: "-" },
    { nama: "Isolasi", tipe: "12mm/Kecil", ukuran: "-", merk: "NachiTape, dll.", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Isolasi", tipe: "12mm/Besar", ukuran: "-", merk: "NachiTape, dll.", hargaEcer: "4.000", hargaPack: "-", keterangan: "-" },
    { nama: "Isolasi", tipe: "24mm", ukuran: "-", merk: "NachiTape, dll.", hargaEcer: "6.000", hargaPack: "-", keterangan: "-" },
    { nama: "Isolasi", tipe: "Bening/Besar", ukuran: "-", merk: "NachiTape, dll.", hargaEcer: "8.000", hargaPack: "-", keterangan: "-" },
    { nama: "Isolasi", tipe: "Coklat/Besar", ukuran: "-", merk: "Berry Tape", hargaEcer: "10.000", hargaPack: "-", keterangan: "-" },
    { nama: "Isolasi", tipe: "Kertas/Kecil", ukuran: "-", merk: "Berry Tape", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Isolasi", tipe: "Kertas/Sedang", ukuran: "-", merk: "Berry Tape", hargaEcer: "5.000", hargaPack: "-", keterangan: "-" },
    { nama: "Isolasi", tipe: "Kertas/Sedang", ukuran: "-", merk: "Safari", hargaEcer: "6.000", hargaPack: "-", keterangan: "-" },
    { nama: "Isolasi", tipe: "Listrik/Kecil", ukuran: "-", merk: "NachiTape, dll.", hargaEcer: "4.000", hargaPack: "-", keterangan: "-" },
    { nama: "Isolasi", tipe: "Hitam/Sedang", ukuran: "-", merk: "NachiTape, dll.", hargaEcer: "12.000", hargaPack: "-", keterangan: "-" },
    { nama: "Isolasi", tipe: "Hitam/Besar", ukuran: "-", merk: "NachiTape, dll.", hargaEcer: "15.000", hargaPack: "-", keterangan: "-" },
    { nama: "Jangka", tipe: "-", ukuran: "-", merk: "Joyko", hargaEcer: "10.000", hargaPack: "-", keterangan: "-" },
    { nama: "Kalkulator", tipe: "Mini", ukuran: "-", merk: "-", hargaEcer: "15.000", hargaPack: "-", keterangan: "-" },
    { nama: "Kalkulator", tipe: "Scientific", ukuran: "-", merk: "-", hargaEcer: "35.000", hargaPack: "-", keterangan: "-" },
    { nama: "Kapur Papan Tulis", tipe: "Warna", ukuran: "-", merk: "Trisensa", hargaEcer: "12.000", hargaPack: "-", keterangan: "-" },
    { nama: "Kapur Papan Tulis", tipe: "Polos", ukuran: "-", merk: "Trisensa", hargaEcer: "5.000", hargaPack: "-", keterangan: "-" },
    { nama: "Kapur Semut", tipe: "-", ukuran: "-", merk: "Bagus", hargaEcer: "4.000", hargaPack: "-", keterangan: "-" },
    { nama: "Klip Jumbo", tipe: "Ecer", ukuran: "-", merk: "V-Tec", hargaEcer: "1.500", hargaPack: "-", keterangan: "-" },
    { nama: "Klip Kertas (Binder)", tipe: "280", ukuran: "-", merk: "BIG", hargaEcer: "5.000", hargaPack: "-", keterangan: "-" },
    { nama: "Klip Kertas (Binder)", tipe: "260", ukuran: "-", merk: "BIG", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Klip Kertas (Binder)", tipe: "200", ukuran: "-", merk: "BIG", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Klip Kertas (Binder)", tipe: "155", ukuran: "-", merk: "BIG", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Klip Kertas (Binder)", tipe: "111", ukuran: "-", merk: "BIG", hargaEcer: "1.000", hargaPack: "-", keterangan: "-" },
    { nama: "Klip Kertas (Binder)", tipe: "107", ukuran: "-", merk: "BIG", hargaEcer: "1.000", hargaPack: "-", keterangan: "-" },
    { nama: "Klip Kertas (Binder)", tipe: "105", ukuran: "-", merk: "BIG", hargaEcer: "1.000", hargaPack: "-", keterangan: "-" },
    { nama: "Klip Trigonal", tipe: "1box Plastik", ukuran: "-", merk: "BIG", hargaEcer: "6.000", hargaPack: "-", keterangan: "-" },
    { nama: "Klip Trigonal", tipe: "1box Kardus", ukuran: "-", merk: "BIG", hargaEcer: "4.000", hargaPack: "-", keterangan: "-" },
    { nama: "Klip Trigonal", tipe: "1 Plastik/4pcs", ukuran: "-", merk: "-", hargaEcer: "1.000", hargaPack: "-", keterangan: "-" },
    { nama: "Klip Vinyl", tipe: "Warna", ukuran: "-", merk: "ZRM", hargaEcer: "5.000", hargaPack: "-", keterangan: "-" },
    { nama: "Kuas", tipe: "1 set", ukuran: "-", merk: "Vis-1", hargaEcer: "9.000", hargaPack: "-", keterangan: "-" },
    { nama: "Kuas", tipe: "1 set", ukuran: "-", merk: "Combo", hargaEcer: "8.000", hargaPack: "-", keterangan: "-" },
    { nama: "Kuas", tipe: "1-2", ukuran: "-", merk: "Ecer", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Kuas", tipe: "3", ukuran: "-", merk: "Ecer", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Kuas", tipe: "7", ukuran: "-", merk: "Ecer", hargaEcer: "4.000", hargaPack: "-", keterangan: "-" },
    { nama: "Kuas", tipe: "8-9", ukuran: "-", merk: "Ecer", hargaEcer: "5.000", hargaPack: "-", keterangan: "-" },
    { nama: "Kuas", tipe: "10", ukuran: "-", merk: "Ecer", hargaEcer: "6.000", hargaPack: "-", keterangan: "-" },
    { nama: "Lem Cair", tipe: "Kecil", ukuran: "-", merk: "Povinal", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Lem Cair", tipe: "Besar", ukuran: "-", merk: "Povinal", hargaEcer: "6.000", hargaPack: "-", keterangan: "-" },
    { nama: "Lem Cair", tipe: "-", ukuran: "-", merk: "Castol", hargaEcer: "7.000", hargaPack: "-", keterangan: "-" },
    { nama: "Lem Cair", tipe: "-", ukuran: "-", merk: "UHU", hargaEcer: "9.000", hargaPack: "-", keterangan: "-" },
    { nama: "Lem Cair", tipe: "-", ukuran: "-", merk: "Alteco", hargaEcer: "5.500", hargaPack: "-", keterangan: "-" },
    { nama: "Lem Cair", tipe: "Kecil", ukuran: "-", merk: "Fox", hargaEcer: "11.000", hargaPack: "-", keterangan: "-" },
    { nama: "Lem Cair", tipe: "Besar", ukuran: "-", merk: "Fox", hargaEcer: "11.000", hargaPack: "-", keterangan: "-" },
    { nama: "Lem Cair", tipe: "-", ukuran: "-", merk: "Grebeell", hargaEcer: "6.000", hargaPack: "-", keterangan: "-" },
    { nama: "Lem G", tipe: "-", ukuran: "-", merk: "G", hargaEcer: "7.000", hargaPack: "-", keterangan: "-" },
    { nama: "Lem Stick", tipe: "Kecil", ukuran: "-", merk: "Joyko", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Lem Stick", tipe: "Besar", ukuran: "-", merk: "-", hargaEcer: "6.000", hargaPack: "-", keterangan: "-" },
    { nama: "Lem Stick", tipe: "Kecil", ukuran: "-", merk: "UHU", hargaEcer: "11.000", hargaPack: "-", keterangan: "-" },
    { nama: "Lem Tembak", tipe: "-", ukuran: "-", merk: "Mi - One", hargaEcer: "22.000", hargaPack: "-", keterangan: "-" },
    { nama: "Magnetis Bookmark", tipe: "CX-005", ukuran: "-", merk: "-", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Palet Lukis", tipe: "-", ukuran: "-", merk: "Butterfly", hargaEcer: "6.000", hargaPack: "-", keterangan: "-" },
    { nama: "Penggaris", tipe: "15cm", ukuran: "-", merk: "Kayagi/No merk", hargaEcer: "2.500", hargaPack: "-", keterangan: "-" },
    { nama: "Penggaris", tipe: "20cm", ukuran: "-", merk: "V-Tec", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Penggaris", tipe: "30cm", ukuran: "-", merk: "Gasta dsb.", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Penggaris", tipe: "30cm", ukuran: "-", merk: "Butterfly", hargaEcer: "4.000", hargaPack: "-", keterangan: "-" },
    { nama: "Penggaris", tipe: "1 Set 4pcs", ukuran: "-", merk: "-", hargaEcer: "7.000", hargaPack: "-", keterangan: "-" },
    { nama: "Penghapus", tipe: "Kecil", ukuran: "-", merk: "BIG dll.", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Penghapus", tipe: "Besar", ukuran: "-", merk: "BIG dll.", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Penghapus Papan", tipe: "-", ukuran: "-", merk: "Kenjoy", hargaEcer: "5.000", hargaPack: "-", keterangan: "-" },
    { nama: "Pines", tipe: "-", ukuran: "-", merk: "ZRM", hargaEcer: "4.000", hargaPack: "-", keterangan: "-" },
    { nama: "Pines", tipe: "-", ukuran: "-", merk: "A+Z", hargaEcer: "5.000", hargaPack: "-", keterangan: "-" },
    { nama: "Pines", tipe: "-", ukuran: "-", merk: "Thumb Tacks", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Rautan", tipe: "-", ukuran: "-", merk: "BIG", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Rautan Duduk", tipe: "-", ukuran: "-", merk: "Kenko", hargaEcer: "30.000", hargaPack: "-", keterangan: "-" },
    { nama: "Silet", tipe: "-", ukuran: "-", merk: "Tatra", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Staples", tipe: "Kecil", ukuran: "-", merk: "Joyko", hargaEcer: "8.000", hargaPack: "-", keterangan: "-" },
    { nama: "Staples", tipe: "Besar", ukuran: "-", merk: "Joyko", hargaEcer: "10.000", hargaPack: "-", keterangan: "-" },
    { nama: "Staples", tipe: "-", ukuran: "-", merk: "Debozz", hargaEcer: "25.000", hargaPack: "-", keterangan: "-" },
    { nama: "Tempat Pensil", tipe: "Kain Kecil", ukuran: "-", merk: "-", hargaEcer: "20.000", hargaPack: "-", keterangan: "-" },
    { nama: "Tempat Pensil", tipe: "Kain Besar", ukuran: "-", merk: "-", hargaEcer: "20.000", hargaPack: "-", keterangan: "-" },
    { nama: "Tempat Pensil", tipe: "Besi", ukuran: "-", merk: "-", hargaEcer: "18.000", hargaPack: "-", keterangan: "-" },
    { nama: "Tinta Stempel", tipe: "Merah/Kecil", ukuran: "-", merk: "A+Z", hargaEcer: "10.000", hargaPack: "-", keterangan: "-" },
    { nama: "Tinta Stempel", tipe: "Biru/Kecil", ukuran: "-", merk: "A+Z", hargaEcer: "10.000", hargaPack: "-", keterangan: "-" },
    { nama: "Tinta Stempel", tipe: "Ungu/Kecil", ukuran: "-", merk: "A+Z", hargaEcer: "10.000", hargaPack: "-", keterangan: "-" },
    { nama: "Tinta Stempel", tipe: "Ungu/Besar", ukuran: "-", merk: "Yamura", hargaEcer: "14.000", hargaPack: "-", keterangan: "-" },
    { nama: "Bolpoin", tipe: "Warna/Hitam", ukuran: "-", merk: "Apel", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Bolpoin", tipe: "Softline 1900", ukuran: "-", merk: "Artline", hargaEcer: "10.000", hargaPack: "-", keterangan: "-" },
    { nama: "Bolpoin", tipe: "-", ukuran: "-", merk: "Bolpenku", hargaEcer: "1.000", hargaPack: "-", keterangan: "-" },
    { nama: "Bolpoin", tipe: "C600", ukuran: "-", merk: "Faster", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Bolpoin", tipe: "F3", ukuran: "-", merk: "Faster", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Bolpoin", tipe: "C6", ukuran: "-", merk: "Faster", hargaEcer: "4.000", hargaPack: "-", keterangan: "-" },
    { nama: "Bolpoin", tipe: "HS866", ukuran: "-", merk: "Hi-Tech", hargaEcer: "4.000", hargaPack: "-", generic: "-", keterangan: "-" },
    { nama: "Bolpoin", tipe: "JK-100", ukuran: "-", merk: "Joyko", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Bolpoin", tipe: "GP243", ukuran: "-", merk: "Joyko", hargaEcer: "4.000", hargaPack: "-", keterangan: "-" },
    { nama: "Bolpoin", tipe: "BP 199", ukuran: "-", merk: "Joyko", hargaEcer: "5.000", hargaPack: "-", keterangan: "-" },
    { nama: "Bolpoin", tipe: "GPC299", ukuran: "-", merk: "Joyko", hargaEcer: "4.000", hargaPack: "-", keterangan: "-" },
    { nama: "Bolpoin", tipe: "K-200", ukuran: "-", merk: "Kenko", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Bolpoin", tipe: "K-1", ukuran: "-", merk: "Kenko", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Bolpoin", tipe: "Warna/Hitam", ukuran: "-", merk: "Kokoro", hargaEcer: "7.000", hargaPack: "-", keterangan: "-" },
    { nama: "Bolpoin", tipe: "Warna/Hitam/BPTP", ukuran: "-", merk: "Pilot", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Bolpoin", tipe: "Picolo", ukuran: "-", merk: "Zebra", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Bolpoin", tipe: "-", ukuran: "-", merk: "Pororo", hargaEcer: "5.000", hargaPack: "-", keterangan: "-" },
    { nama: "Bolpoin", tipe: "S1", ukuran: "-", merk: "Snowman", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Bolpoin", tipe: "V3", ukuran: "-", merk: "Snowman", hargaEcer: "4.000", hargaPack: "-", keterangan: "-" },
    { nama: "Bolpoin", tipe: "Vision 2", ukuran: "-", merk: "Snowman", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Bolpoin", tipe: "Warna/Polos/AE7", ukuran: "-", merk: "Standart", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Bolpoin", tipe: "P5", ukuran: "-", merk: "Standart", hargaEcer: "4.000", hargaPack: "-", keterangan: "-" },
    { nama: "Bolpoin", tipe: "B'Live", ukuran: "-", merk: "Standart", hargaEcer: "4.000", hargaPack: "-", keterangan: "-" },
    { nama: "Bolpoin", tipe: "Warna/Polos", ukuran: "-", merk: "Weiyada", hargaEcer: "6.000", hargaPack: "-", keterangan: "-" },
    { nama: "Bolpoin", tipe: "Penciltic", ukuran: "-", merk: "Zebra", hargaEcer: "6.000", hargaPack: "-", keterangan: "-" },
    { nama: "Bolpoin", tipe: "C6000", ukuran: "-", merk: "Queens", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Isi Bolpoin", tipe: "-", ukuran: "-", merk: "-", hargaEcer: "-", hargaPack: "-", keterangan: "-" },
    { nama: "Pensil", tipe: "HB", ukuran: "-", merk: "Staedtler", hargaEcer: "5.000", hargaPack: "-", keterangan: "-" },
    { nama: "Pensil", tipe: "Platinum 5000", ukuran: "-", merk: "Benefit", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Pensil", tipe: "2B", ukuran: "-", merk: "Faber Catell", hargaEcer: "5.000", hargaPack: "-", keterangan: "-" },
    { nama: "Pensil", tipe: "4B - 8B", ukuran: "-", merk: "Faber Catell", hargaEcer: "6.000", hargaPack: "-", keterangan: "-" },
    { nama: "Pensil", tipe: "2B", ukuran: "-", merk: "Greebel", hargaEcer: "2.500", hargaPack: "-", keterangan: "-" },
    { nama: "Pensil", tipe: "P-93", ukuran: "-", merk: "Joyko", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Pensil", tipe: "0810", ukuran: "-", merk: "Kenko", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Pensil", tipe: "TF 6388", ukuran: "-", merk: "Trifelo", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Pensil Mekanik", tipe: "MP-7013", ukuran: "-", merk: "Benefit", hargaEcer: "6.000", hargaPack: "-", keterangan: "-" },
    { nama: "Pensil Mekanik", tipe: "MP-22", ukuran: "-", merk: "Benefit", hargaEcer: "4.500", hargaPack: "-", keterangan: "-" },
    { nama: "Pensil Mekanik", tipe: "BP-338", ukuran: "-", merk: "Joyko", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Pensil Mekanik", tipe: "SF-202", ukuran: "-", merk: "Safari", hargaEcer: "4.000", hargaPack: "-", keterangan: "-" },
    { nama: "Pensil Mekanik", tipe: "MP02", ukuran: "-", merk: "Eselon", hargaEcer: "4.000", hargaPack: "-", keterangan: "-" },
    { nama: "Isi Pensil", tipe: "0,5", ukuran: "-", merk: "Joyko", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Isi Pensil", tipe: "0,7", ukuran: "-", merk: "Joyko", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Isi Pensil", tipe: "0,7", ukuran: "-", merk: "Faber Catell", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Spidol Non Permanent", tipe: "Kecil", ukuran: "-", merk: "Snowman", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Spidol Non Permanent", tipe: "Kecil", ukuran: "-", merk: "Artline", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Spidol Non Permanent", tipe: "900XF", ukuran: "-", merk: "Artline", hargaEcer: "17.000", hargaPack: "-", keterangan: "-" },
    { nama: "Spidol Non Permanent", tipe: "400XF", ukuran: "-", merk: "Artline", hargaEcer: "17.000", hargaPack: "-", keterangan: "-" },
    { nama: "Spidol Non Permanent", tipe: "EK-231N", ukuran: "-", merk: "Artline", hargaEcer: "11.000", hargaPack: "-", keterangan: "-" },
    { nama: "Spidol Non Permanent", tipe: "990XF", ukuran: "-", merk: "Artline", hargaEcer: "15.000", hargaPack: "-", keterangan: "-" },
    { nama: "Spidol Non Permanent", tipe: "Hijau", ukuran: "-", merk: "Montana", hargaEcer: "5.000", hargaPack: "-", keterangan: "-" },
    { nama: "Spidol Non Permanent", tipe: "White", ukuran: "-", merk: "Snowman", hargaEcer: "17.000", hargaPack: "-", keterangan: "-" },
    { nama: "Spidol Non Permanent", tipe: "FT700", ukuran: "-", merk: "Snowman", hargaEcer: "10.000", hargaPack: "-", keterangan: "-" },
    { nama: "Spidol Non Permanent", tipe: "Merah", ukuran: "-", merk: "Snowman", hargaEcer: "8.500", hargaPack: "-", keterangan: "-" },
    { nama: "Spidol Non Permanent", tipe: "Putih", ukuran: "-", merk: "Snowman", hargaEcer: "15.000", hargaPack: "-", keterangan: "-" },
    { nama: "Spidol Non Permanent", tipe: "Hitam", ukuran: "-", merk: "Snowman", hargaEcer: "8.000", hargaPack: "-", keterangan: "-" },
    { nama: "Spidol Non Permanent", tipe: "12 warna", ukuran: "-", merk: "Snowman", hargaEcer: "17.000", hargaPack: "-", keterangan: "-" },
    { nama: "Spidol Permanent", tipe: "Hitam", ukuran: "-", merk: "Snowman", hargaEcer: "7.000", hargaPack: "-", keterangan: "-" },
    { nama: "Spidol Permanent", tipe: "Biru", ukuran: "-", merk: "Snowman", hargaEcer: "8.000", hargaPack: "-", keterangan: "-" },
    { nama: "Spidol Permanent", tipe: "Biru", ukuran: "-", merk: "Artline", hargaEcer: "8.000", hargaPack: "-", keterangan: "-" },
    { nama: "Isi Spidol Permanent", tipe: "Hitam", ukuran: "-", merk: "Snowman", hargaEcer: "15.000", hargaPack: "-", keterangan: "-" },
    { nama: "Isi Spidol Non Permanent", tipe: "Hitam", ukuran: "-", merk: "Snowman", hargaEcer: "18.000", hargaPack: "-", keterangan: "-" },
    { nama: "Pensil Warna", tipe: "-", ukuran: "-", merk: "Joyko", hargaEcer: "8.500", hargaPack: "-", keterangan: "-" },
    { nama: "Krayon", tipe: "Oil Pastels", ukuran: "-", merk: "Greebel", hargaEcer: "30.000", hargaPack: "-", keterangan: "-" },
    { nama: "Krayon", tipe: "Pensil", ukuran: "-", merk: "Titi", hargaEcer: "16.000", hargaPack: "-", keterangan: "-" },
    { nama: "Baterai", tipe: "AA", ukuran: "-", merk: "Alkaline", hargaEcer: "6.000", hargaPack: "-", keterangan: "-" },
    { nama: "Baterai", tipe: "AAA", ukuran: "-", merk: "Alkaline", hargaEcer: "7.000", hargaPack: "-", keterangan: "-" },
    { nama: "Baterai", tipe: "AA", ukuran: "-", merk: "ABC", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Benang Jahit", tipe: "-", ukuran: "-", merk: "Butterfly", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Benang Woll", tipe: "-", ukuran: "-", merk: "-", hargaEcer: "10.000", hargaPack: "-", keterangan: "-" },
    { nama: "Bendera", tipe: "Merah Putih", ukuran: "-", merk: "-", hargaEcer: "1.000", hargaPack: "-", keterangan: "-" },
    { nama: "Cermin", tipe: "-", ukuran: "-", merk: "-", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Clay", tipe: "Kecil", ukuran: "-", merk: "-", hargaEcer: "6.000", hargaPack: "-", keterangan: "-" },
    { nama: "Clay", tipe: "Besar", ukuran: "-", merk: "-", hargaEcer: "9.000", hargaPack: "-", keterangan: "-" },
    { nama: "Corrugated Paper", tipe: "-", ukuran: "-", merk: "Kokoro", hargaEcer: "15.000", hargaPack: "-", keterangan: "-" },
    { nama: "Cotton Bud", tipe: "-", ukuran: "-", merk: "All", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Gantungan Kunci", tipe: "Kecil", ukuran: "-", merk: "-", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Gantungan Kunci", tipe: "Tali Tanpa Inisial", ukuran: "-", merk: "-", hargaEcer: "8.000", hargaPack: "-", keterangan: "-" },
    { nama: "Gantungan Kunci", tipe: "Tali + Inisial", ukuran: "-", merk: "-", hargaEcer: "9.000", hargaPack: "-", keterangan: "-" },
    { nama: "Gantungan Kunci", tipe: "Boneka Karet", ukuran: "-", merk: "-", hargaEcer: "8.000", hargaPack: "-", keterangan: "-" },
    { nama: "Gantungan Kunci", tipe: "Panda", ukuran: "-", merk: "-", hargaEcer: "9.000", hargaPack: "-", keterangan: "-" },
    { nama: "Glitter", tipe: "-", ukuran: "-", merk: "-", hargaEcer: "4.000", hargaPack: "-", keterangan: "-" },
    { nama: "Gunting kuku", tipe: "Kecil", ukuran: "-", merk: "-", hargaEcer: "4.000", hargaPack: "-", keterangan: "-" },
    { nama: "Gunting kuku", tipe: "Besar", ukuran: "-", merk: "-", hargaEcer: "8.000", hargaPack: "-", keterangan: "-" },
    { nama: "Id Card", tipe: "Klip Kartu Plastik", ukuran: "-", merk: "-", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Id Card", tipe: "Klip Kartu Besi", ukuran: "-", merk: "-", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Id Card", tipe: "Yoyo/Warna Warni", ukuran: "-", merk: "-", hargaEcer: "4.000", hargaPack: "-", keterangan: "-" },
    { nama: "Id Card", tipe: "Holder + Tali/54x85mm", ukuran: "-", merk: "-", hargaEcer: "4.500", hargaPack: "-", keterangan: "-" },
    { nama: "Id Card", tipe: "Plastik/A1", ukuran: "-", merk: "BIG", hargaEcer: "2.000", hargaPack: "15.000", keterangan: "-" },
    { nama: "Id Card", tipe: "Plastik/A2", ukuran: "-", merk: "BIG", hargaEcer: "2.000", hargaPack: "16.000", keterangan: "-" },
    { nama: "Id Card", tipe: "Plastik/A3", ukuran: "-", merk: "BIG", hargaEcer: "2.000", hargaPack: "18.000", keterangan: "-" },
    { nama: "Id Card", tipe: "Plastik/B1", ukuran: "-", merk: "BIG", hargaEcer: "2.000", hargaPack: "15.000", keterangan: "-" },
    { nama: "Id Card", tipe: "Plastik/B2", ukuran: "-", merk: "BIG", hargaEcer: "2.000", hargaPack: "17.000", keterangan: "-" },
    { nama: "Id Card", tipe: "Plastik/B3", ukuran: "-", merk: "BIG", hargaEcer: "2.000", hargaPack: "18.000", keterangan: "-" },
    { nama: "Id Card", tipe: "Plastik/B4", ukuran: "-", merk: "BIG", hargaEcer: "2.500", hargaPack: "23.000", keterangan: "-" },
    { nama: "Id Card", tipe: "Holder Plastik/Satuan", ukuran: "-", merk: "-", hargaEcer: "2.500", hargaPack: "-", keterangan: "-" },
    { nama: "Id Card", tipe: "Tali Keplek/Kecil", ukuran: "-", merk: "-", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Id Card", tipe: "Tali Keplek/Besar", ukuran: "-", merk: "-", hargaEcer: "4.500", hargaPack: "-", keterangan: "-" },
    { nama: "Jarum Jahit", tipe: "-", ukuran: "-", merk: "-", hargaEcer: "3.500", hargaPack: "-", keterangan: "-" },
    { nama: "Jarum Pentul", tipe: "Kecil", ukuran: "-", merk: "-", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Jarum Pentul", tipe: "Besar", ukuran: "-", merk: "-", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Jepit Rambut", tipe: "Motif", ukuran: "-", merk: "-", hargaEcer: "7.500", hargaPack: "-", keterangan: "-" },
    { nama: "Jepit Rambut", tipe: "Polos", ukuran: "-", merk: "-", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Kabel", tipe: "Type C", ukuran: "-", merk: "Veger", hargaEcer: "20.000", hargaPack: "-", keterangan: "-" },
    { nama: "Kabel", tipe: "Micro", ukuran: "-", merk: "Veger", hargaEcer: "15.000", hargaPack: "-", keterangan: "-" },
    { nama: "Kabel", tipe: "Lightning", ukuran: "-", merk: "Veger", hargaEcer: "20.000", hargaPack: "-", keterangan: "-" },
    { nama: "Kabel", tipe: "Headphone/Headset", ukuran: "-", merk: "U Music 19", hargaEcer: "10.000", hargaPack: "-", keterangan: "-" },
    { nama: "Kain Flanel", tipe: "-", ukuran: "-", merk: "-", hargaEcer: "2.500", hargaPack: "-", keterangan: "-" },
    { nama: "Kanvas", tipe: "20x30cm", ukuran: "-", merk: "-", hargaEcer: "12.000", hargaPack: "-", keterangan: "-" },
    { nama: "Kanvas", tipe: "30x30cm", ukuran: "-", merk: "-", hargaEcer: "15.000", hargaPack: "-", keterangan: "-" },
    { nama: "Kanvas", tipe: "30x40cm", ukuran: "-", merk: "-", hargaEcer: "18.000", hargaPack: "-", keterangan: "-" },
    { nama: "Kawat Bulu", tipe: "-", ukuran: "-", merk: "-", hargaEcer: "1.000", hargaPack: "-", keterangan: "-" },
    { nama: "Lilin", tipe: "Putih", ukuran: "-", merk: "-", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Lilin Ulang Tahun", tipe: "Spiral/Kecil", ukuran: "-", merk: "-", hargaEcer: "4.000", hargaPack: "-", keterangan: "-" },
    { nama: "Masker", tipe: "-", ukuran: "-", merk: "-", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Paper Bag", tipe: "Kecil (Coklat)", ukuran: "-", merk: "-", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Paper Bag", tipe: "Sedang", ukuran: "-", merk: "-", hargaEcer: "7.500", hargaPack: "-", keterangan: "-" },
    { nama: "Paper Bag", tipe: "Sedang Corak", ukuran: "-", merk: "-", hargaEcer: "12.000", hargaPack: "-", keterangan: "-" },
    { nama: "Paper Bag", tipe: "Besar", ukuran: "-", merk: "-", hargaEcer: "8.000", hargaPack: "-", keterangan: "-" },
    { nama: "Paper Bag", tipe: "Extra Besar", ukuran: "-", merk: "-", hargaEcer: "10.000", hargaPack: "-", keterangan: "-" },
    { nama: "Pencukur Kumis", tipe: "Biru", ukuran: "-", merk: "Gillette", hargaEcer: "10.000", hargaPack: "-", keterangan: "-" },
    { nama: "Pencukur Kumis", tipe: "Kuning", ukuran: "-", merk: "Gillette", hargaEcer: "7.000", hargaPack: "-", keterangan: "-" },
    { nama: "Peniti", tipe: "Besar", ukuran: "-", merk: "-", hargaEcer: "7.000", hargaPack: "-", keterangan: "-" },
    { nama: "Peniti", tipe: "Orlet Kuning/Putih", ukuran: "-", merk: "-", hargaEcer: "1.000", hargaPack: "-", keterangan: "-" },
    { nama: "Peniti", tipe: "Biting Swam 12pcs", ukuran: "-", merk: "-", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Peniti", tipe: "Bros", ukuran: "-", merk: "-", hargaEcer: "1.000", hargaPack: "-", keterangan: "-" },
    { nama: "Pinset", tipe: "-", ukuran: "-", merk: "-", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Pita Pull Bow Ribbon", tipe: "-", ukuran: "-", merk: "-", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Pita Satin", tipe: "0,5cm/Meter", ukuran: "-", merk: "-", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Pita Satin", tipe: "1,5cm", ukuran: "-", merk: "-", hargaEcer: "6.500", hargaPack: "-", keterangan: "-" },
    { nama: "Pita Satin", tipe: "2,5cm", ukuran: "-", merk: "-", hargaEcer: "10.000", hargaPack: "-", keterangan: "-" },
    { nama: "Pita Satin", tipe: "2cm", ukuran: "-", merk: "-", hargaEcer: "9.000", hargaPack: "-", keterangan: "-" },
    { nama: "Pita Satin", tipe: "Merah Putih", ukuran: "-", merk: "-", hargaEcer: "9.000", hargaPack: "-", keterangan: "-" },
    { nama: "Plastik", tipe: "STNK", ukuran: "-", merk: "-", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Plastik", tipe: "KTP", ukuran: "-", merk: "-", hargaEcer: "1.000", hargaPack: "-", keterangan: "-" },
    { nama: "Plastik", tipe: "Press Mika/A4", ukuran: "-", merk: "-", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Plastisin/Malam", tipe: "Kecil", ukuran: "-", merk: "-", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Plastisin/Malam", tipe: "Besar", ukuran: "-", merk: "-", hargaEcer: "8.000", hargaPack: "-", keterangan: "-" },
    { nama: "Rumbai", tipe: "Kecil", ukuran: "-", merk: "All", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Rumbai", tipe: "Besar", ukuran: "-", merk: "All", hargaEcer: "10.000", hargaPack: "-", keterangan: "-" },
    { nama: "Sarung Tangan", tipe: "-", ukuran: "-", merk: "All", hargaEcer: "8.500", hargaPack: "-", keterangan: "-" },
    { nama: "Stick ice Cream", tipe: "Polos", ukuran: "-", merk: "-", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Stick ice Cream", tipe: "Warna", ukuran: "-", merk: "-", hargaEcer: "4.000", hargaPack: "-", keterangan: "-" },
    { nama: "Sticker Dinding", tipe: "-", ukuran: "-", merk: "-", hargaEcer: "12.000", hargaPack: "-", keterangan: "-" },
    { nama: "Sticker Label", tipe: "-", ukuran: "-", merk: "-", hargaEcer: "9.000", hargaPack: "-", keterangan: "-" },
    { nama: "Strip Masker", tipe: "Tali", ukuran: "-", merk: "madebymi", hargaEcer: "6.000", hargaPack: "-", keterangan: "-" },
    { nama: "Strip Masker", tipe: "Manik Manik", ukuran: "-", merk: "madebymi", hargaEcer: "13.000", hargaPack: "-", keterangan: "-" },
    { nama: "Strip Masker", tipe: "Tali", ukuran: "-", merk: "No Merk", hargaEcer: "7.000", hargaPack: "-", keterangan: "-" },
    { nama: "Tali Rambut", tipe: "Polos", ukuran: "-", merk: "-", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Tali Rambut", tipe: "Motif", ukuran: "-", merk: "-", hargaEcer: "7.000", hargaPack: "-", keterangan: "-" },
    { nama: "Tirai Dekorasi Pesta", tipe: "-", ukuran: "-", merk: "Vis-1", hargaEcer: "16.000", hargaPack: "-", keterangan: "-" },
    { nama: "Tisu", tipe: "Basah", ukuran: "-", merk: "-", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Tisu", tipe: "Kering/Kecil", ukuran: "-", merk: "-", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Tisu", tipe: "Kering/Besar", ukuran: "-", merk: "-", hargaEcer: "6.000", hargaPack: "-", keterangan: "-" },
    { nama: "Twis Tie", tipe: "-", ukuran: "-", merk: "-", hargaEcer: "5.000", hargaPack: "-", keterangan: "-" },
    { nama: "Uno", tipe: "-", ukuran: "-", merk: "-", hargaEcer: "12.500", hargaPack: "-", keterangan: "-" },
    { nama: "Wash Bag", tipe: "Kecil", ukuran: "-", merk: "-", hargaEcer: "5.000", hargaPack: "-", keterangan: "-" },
    { nama: "Wash Bag", tipe: "Besar", ukuran: "-", merk: "-", hargaEcer: "5.500", hargaPack: "-", keterangan: "-" },
    { nama: "HVS 75gsm", tipe: "Putih/A4", ukuran: "-", merk: "All", hargaEcer: "250", hargaPack: "50.000", keterangan: "-" },
    { nama: "HVS 75gsm", tipe: "Putih/F4", ukuran: "-", merk: "All", hargaEcer: "250", hargaPack: "50.000", keterangan: "-" },
    { nama: "HVS 75gsm", tipe: "Warna/A4", ukuran: "-", merk: "All", hargaEcer: "500", hargaPack: "-", keterangan: "-" },
    { nama: "HVS 75gsm", tipe: "Warna/F4", ukuran: "-", merk: "All", hargaEcer: "500", hargaPack: "-", keterangan: "-" },
    { nama: "HVS 75gsm", tipe: "Putih/A3", ukuran: "-", merk: "All", hargaEcer: "1.000", hargaPack: "-", keterangan: "-" },
    { nama: "HVS 75gsm", tipe: "Putih/A5", ukuran: "-", merk: "All", hargaEcer: "500", hargaPack: "-", keterangan: "-" },
    { nama: "Sticker", tipe: "Glossy/A4", ukuran: "-", merk: "All", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Sticker", tipe: "Glossy/A3", ukuran: "-", merk: "All", hargaEcer: "5.000", hargaPack: "-", keterangan: "-" },
    { nama: "Sticker", tipe: "Bontax/A4", ukuran: "-", merk: "All", hargaEcer: "2.500", hargaPack: "-", keterangan: "-" },
    { nama: "Sticker", tipe: "Bontax/A3", ukuran: "-", merk: "All", hargaEcer: "6.000", hargaPack: "-", keterangan: "-" },
    { nama: "Photo Paper", tipe: "Silky/Doff/A4", ukuran: "-", merk: "All", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Art Paper", tipe: "Glossy/A4", ukuran: "-", merk: "All", hargaEcer: "4.000", hargaPack: "-", keterangan: "-" },
    { nama: "Art Paper", tipe: "Glossy/A3", ukuran: "-", merk: "All", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Art Paper", tipe: "Glossy/A3+", ukuran: "-", merk: "All", hargaEcer: "5.000", hargaPack: "-", keterangan: "-" },
    { nama: "Buffallo", tipe: "1-3 Lembar/Semua Warna", ukuran: "-", merk: "All", hargaEcer: "1.000", hargaPack: "-", keterangan: "-" },
    { nama: "Buffallo", tipe: "4-10 Lembar/Semua Warna", ukuran: "-", merk: "All", hargaEcer: "700", hargaPack: "-", keterangan: "-" },
    { nama: "Buffallo", tipe: "100 Lembar/Semua Warna", ukuran: "-", merk: "All", hargaEcer: "32.000", hargaPack: "-", keterangan: "-" },
    { nama: "Kado", tipe: "Kado/Kecil", ukuran: "-", merk: "All", hargaEcer: "2.500", hargaPack: "-", keterangan: "-" },
    { nama: "Kado", tipe: "Kado/Besar", ukuran: "-", merk: "All", hargaEcer: "5.000", hargaPack: "-", keterangan: "-" },
    { nama: "Karton", tipe: "Tebal", ukuran: "-", merk: "All", hargaEcer: "10.000", hargaPack: "-", keterangan: "-" },
    { nama: "Karton", tipe: "Tipis", ukuran: "-", merk: "All", hargaEcer: "6.000", hargaPack: "-", keterangan: "-" },
    { nama: "Kertas", tipe: "Asturo", ukuran: "-", merk: "All", hargaEcer: "5.000", hargaPack: "-", keterangan: "-" },
    { nama: "Kertas", tipe: "Buram", ukuran: "-", merk: "All", hargaEcer: "1.000", hargaPack: "-", keterangan: "-" },
    { nama: "Kertas", tipe: "Folio Bergaris/F4", ukuran: "-", merk: "All", hargaEcer: "500", hargaPack: "-", keterangan: "-" },
    { nama: "Kertas", tipe: "Kalkir", ukuran: "-", merk: "All", hargaEcer: "1.500", hargaPack: "-", keterangan: "-" },
    { nama: "Kertas", tipe: "Karbon", ukuran: "-", merk: "All", hargaEcer: "1.000", hargaPack: "-", keterangan: "-" },
    { nama: "Kertas", tipe: "Kilap", ukuran: "-", merk: "All", hargaEcer: "2.500", hargaPack: "-", keterangan: "-" },
    { nama: "Kertas", tipe: "Linen", ukuran: "-", merk: "All", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Kertas", tipe: "Manila/Hitam, Merah, Ungu, Coklat", ukuran: "-", merk: "All", hargaEcer: "4.000", hargaPack: "-", keterangan: "-" },
    { nama: "Kertas", tipe: "Manila/Putih, Kuning, Biru Muda, Hijau Muda", ukuran: "-", merk: "All", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Kertas", tipe: "Sukun", ukuran: "-", merk: "All", hargaEcer: "2.500", hargaPack: "-", keterangan: "-" },
    { nama: "Kwitansi", tipe: "Kecil", ukuran: "-", merk: "All", hargaEcer: "4.000", hargaPack: "-", keterangan: "-" },
    { nama: "Kwitansi", tipe: "Besar", ukuran: "-", merk: "All", hargaEcer: "5.500", hargaPack: "-", keterangan: "-" },
    { nama: "Label Harga", tipe: "-", ukuran: "-", merk: "All", hargaEcer: "1.000", hargaPack: "-", keterangan: "-" },
    { nama: "Map", tipe: "Snail", ukuran: "-", merk: "All", hargaEcer: "4.000", hargaPack: "-", keterangan: "-" },
    { nama: "Map", tipe: "Kancing", ukuran: "-", merk: "All", hargaEcer: "4.000", hargaPack: "-", keterangan: "-" },
    { nama: "Map", tipe: "L", ukuran: "-", merk: "Okey", hargaEcer: "3.000", hargaPack: "20.000", keterangan: "-" },
    { nama: "Map", tipe: "Kertas/Stopmap", ukuran: "-", merk: "All", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Map", tipe: "Kertas/Stopmap/50 Pcs", ukuran: "-", merk: "All", hargaEcer: "52.000", hargaPack: "-", keterangan: "-" },
    { nama: "Map", tipe: "Diamond", ukuran: "-", merk: "All", hargaEcer: "5.000", hargaPack: "-", keterangan: "-" },
    { nama: "Mika", tipe: "Laminating/A4", ukuran: "-", merk: "All", hargaEcer: "5.000", hargaPack: "-", keterangan: "-" },
    { nama: "Mika", tipe: "Laminating/A3", ukuran: "-", merk: "All", hargaEcer: "10.000", hargaPack: "-", keterangan: "-" },
    { nama: "Mika Jilid", tipe: "A4", ukuran: "-", merk: "All", hargaEcer: "2.000", fontPack: "-", keterangan: "-" },
    { nama: "Mika Jilid", tipe: "F4/Warna", ukuran: "-", merk: "All", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Nota", tipe: "1ply/Kecil", ukuran: "-", merk: "All", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Nota", tipe: "2ply/Kecil", ukuran: "-", merk: "All", hargaEcer: "4.000", hargaPack: "-", keterangan: "-" },
    { nama: "Origami", tipe: "14x14cm", ukuran: "-", merk: "All", hargaEcer: "4.000", hargaPack: "-", keterangan: "-" },
    { nama: "Origami", tipe: "Craft14x14cm", ukuran: "-", merk: "All", hargaEcer: "5.000", hargaPack: "-", keterangan: "-" },
    { nama: "Origami", tipe: "16x16mm", ukuran: "-", merk: "All", hargaEcer: "5.000", hargaPack: "-", keterangan: "-" },
    { nama: "Origami", tipe: "Craft/16x16mm", ukuran: "-", merk: "All", hargaEcer: "6.000", hargaPack: "-", keterangan: "-" },
    { nama: "Origami", tipe: "Metalic/16x16mm", ukuran: "-", merk: "All", hargaEcer: "12.000", hargaPack: "-", keterangan: "-" },
    { nama: "Origami", tipe: "18x18cm", ukuran: "-", merk: "All", hargaEcer: "6.000", hargaPack: "-", keterangan: "-" },
    { nama: "Origami", tipe: "20x20mm", ukuran: "-", merk: "All", hargaEcer: "6.500", hargaPack: "-", keterangan: "-" },
    { nama: "Origami", tipe: "15x50mm", ukuran: "-", merk: "Trifello", hargaEcer: "7.000", hargaPack: "-", keterangan: "-" },
    { nama: "Sticky Note", tipe: "38x51mm", ukuran: "-", merk: "BIG", hargaEcer: "5.000", hargaPack: "-", keterangan: "-" },
    { nama: "Sticky Note", tipe: "51x38mm", ukuran: "-", merk: "BIG", hargaEcer: "4.000", hargaPack: "-", keterangan: "-" },
    { nama: "Sticky Note", tipe: "76x76mm", ukuran: "-", merk: "BIG", hargaEcer: "7.000", hargaPack: "-", keterangan: "-" },
    { nama: "Sticky Note", tipe: "76x91mm", ukuran: "-", merk: "BIG", hargaEcer: "-", hargaPack: "-", keterangan: "-" },
    { nama: "Sticky Note", tipe: "50x15mm", ukuran: "-", merk: "BIG", hargaEcer: "-", hargaPack: "-", keterangan: "-" },
    { nama: "Sticky Note", tipe: "76x51mm", ukuran: "-", merk: "BIG", hargaEcer: "6.000", hargaPack: "-", keterangan: "-" },
    { nama: "Sticky Note", tipe: "Transparant/76x76mm", ukuran: "-", merk: "BIG", hargaEcer: "10.000", hargaPack: "-", keterangan: "-" },
    { nama: "Sticky Note", tipe: "Index(Pagar)", ukuran: "-", merk: "BIG", hargaEcer: "9.000", hargaPack: "-", keterangan: "-" },
    { nama: "Sticky Note", tipe: "Motif/15x50mm", ukuran: "-", merk: "-", hargaEcer: "5.000", hargaPack: "-", keterangan: "-" },
    { nama: "Map", tipe: "Resleting + Kancing", ukuran: "-", merk: "-", hargaEcer: "16.000", hargaPack: "-", keterangan: "-" },
    { nama: "Map", tipe: "Full Resleting", ukuran: "-", merk: "-", hargaEcer: "13.000", hargaPack: "-", keterangan: "-" },
    { nama: "Amplop", tipe: "Coklat/Lamaran/Garis", ukuran: "-", merk: "-", hargaEcer: "2.500", hargaPack: "-", keterangan: "-" },
    { nama: "Amplop", tipe: "Coklat/Lamaran/Polos", ukuran: "-", merk: "-", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Amplop", tipe: "Coklat/Dokumen/Sedang", ukuran: "-", merk: "-", hargaEcer: "1.500", hargaPack: "-", keterangan: "-" },
    { nama: "Amplop", tipe: "Coklat/Dokumen/Kecil/Seal @3pcs", ukuran: "-", merk: "-", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Amplop", tipe: "Coklat/Dokumen/Kecil/Non Seal", ukuran: "-", merk: "-", hargaEcer: "1.000", hargaPack: "-", keterangan: "-" },
    { nama: "Amplop", tipe: "104/Seal/Non Booklet", ukuran: "-", merk: "PPLine", hargaEcer: "500", hargaPack: "-", keterangan: "-" },
    { nama: "Amplop", tipe: "110/Seal/Booklet", ukuran: "-", merk: "PPLine", hargaEcer: "500", hargaPack: "-", keterangan: "-" },
    { nama: "Amplop", tipe: "110/Seal/ Non Booklet", ukuran: "-", merk: "PPLine", hargaEcer: "500", hargaPack: "-", keterangan: "-" },
    { nama: "Amplop", tipe: "110/Non Seal/Polos", ukuran: "-", merk: "B'Gain", hargaEcer: "250", hargaPack: "-", keterangan: "-" },
    { nama: "Amplop", tipe: "Besar", ukuran: "-", merk: "Merpati", hargaEcer: "500", hargaPack: "-", keterangan: "-" },
    { nama: "Absen", tipe: "-", ukuran: "-", merk: "-", hargaEcer: "4.000", hargaPack: "-", keterangan: "-" },
    { nama: "Binder", tipe: "Looseleaf/A5", ukuran: "-", merk: "-", hargaEcer: "24.000", hargaPack: "-", keterangan: "-" },
    { nama: "Binder", tipe: "The Coil/A6", ukuran: "-", merk: "-", hargaEcer: "13.000", hargaPack: "-", keterangan: "-" },
    { nama: "Binder", tipe: "E-156/Erica", ukuran: "-", merk: "-", hargaEcer: "6.000", hargaPack: "-", keterangan: "-" },
    { nama: "Binder", tipe: "Diary Fashion", ukuran: "-", merk: "-", hargaEcer: "23.000", hargaPack: "-", keterangan: "-" },
    { nama: "Binder", tipe: "Wengu", ukuran: "-", merk: "-", hargaEcer: "16.000", hargaPack: "-", keterangan: "-" },
    { nama: "Binder", tipe: "Ajp Mart", ukuran: "-", merk: "-", hargaEcer: "20.000", hargaPack: "-", keterangan: "-" },
    { nama: "Binder", tipe: "Np-404/Batik", ukuran: "-", merk: "-", hargaEcer: "6.500", hargaPack: "-", keterangan: "-" },
    { nama: "Buku Akuntansi", tipe: "Isi 50/F4", ukuran: "-", merk: "-", hargaEcer: "14.000", hargaPack: "-", keterangan: "-" },
    { nama: "Buku Akuntansi", tipe: "Isi 100/F4", ukuran: "-", merk: "-", hargaEcer: "18.000", hargaPack: "-", keterangan: "-" },
    { nama: "Buku Akuntansi", tipe: "A5", ukuran: "-", merk: "-", hargaEcer: "12.000", hargaPack: "-", keterangan: "-" },
    { nama: "Buku Akuntansi", tipe: "A6", ukuran: "-", merk: "-", hargaEcer: "7.000", hargaPack: "-", keterangan: "-" },
    { nama: "Buku Gambar", tipe: "A4", ukuran: "-", merk: "Sidu/dll.", hargaEcer: "4.000", hargaPack: "-", keterangan: "-" },
    { nama: "Buku Gambar", tipe: "A3", ukuran: "-", merk: "Sidu/dll.", hargaEcer: "8.000", hargaPack: "-", keterangan: "-" },
    { nama: "Buku Kas", tipe: "Kecil", ukuran: "-", merk: "-", hargaEcer: "10.000", hargaPack: "-", keterangan: "-" },
    { nama: "Buku Kas", tipe: "Besar", ukuran: "-", merk: "-", hargaEcer: "15.000", hargaPack: "-", keterangan: "-" },
    { nama: "Buku Panjang", tipe: "Hard Cover/Folio", ukuran: "-", merk: "-", hargaEcer: "12.000", hargaPack: "-", keterangan: "-" },
    { nama: "Buku Tulis", tipe: "Isi 38/Kecil", ukuran: "-", merk: "Sidu", hargaEcer: "5.000", hargaPack: "35.000", keterangan: "-" },
    { nama: "Buku Tulis", tipe: "Isi 38/Kecil", ukuran: "-", merk: "Skola", hargaEcer: "5.000", hargaPack: "27.000", keterangan: "-" },
    { nama: "Buku Tulis", tipe: "Isi 38/Kecil", ukuran: "-", merk: "Vision", hargaEcer: "5.000", hargaPack: "25.000", keterangan: "-" },
    { nama: "Buku Tulis", tipe: "Isi 58/Kecil", ukuran: "-", merk: "Sidu", hargaEcer: "5.500", hargaPack: "-", keterangan: "-" },
    { nama: "Buku Tulis", tipe: "Kotak Kecil", ukuran: "-", merk: "-", hargaEcer: "5.000", hargaPack: "-", keterangan: "-" },
    { nama: "Buku Tulis", tipe: "Halus", ukuran: "-", merk: "-", hargaEcer: "5.000", hargaPack: "-", keterangan: "-" },
    { nama: "Buku Tulis", tipe: "Isi 36/Besar", ukuran: "-", merk: "Big Boss", hargaEcer: "6.000", hargaPack: "48.000", keterangan: "-" },
    { nama: "Buku Tulis", tipe: "Isi 42/Besar", ukuran: "-", merk: "Big Boss", hargaEcer: "6.500", hargaPack: "36.000", keterangan: "-" },
    { nama: "Buku Tulis", tipe: "Kotak/10mm", ukuran: "-", merk: "-", hargaEcer: "5.000", hargaPack: "-", keterangan: "-" },
    { nama: "Buku Tulis", tipe: "Kotak/14mm", ukuran: "-", merk: "-", hargaEcer: "5.000", hargaPack: "-", keterangan: "-" },
    { nama: "Kwitansi", tipe: "Kecil", ukuran: "-", merk: "-", hargaEcer: "4.000", hargaPack: "-", keterangan: "-" },
    { nama: "Kwitansi", tipe: "Besar", ukuran: "-", merk: "-", hargaEcer: "5.500", hargaPack: "-", keterangan: "-" },
    { nama: "Milimeter Block", tipe: "-", ukuran: "-", merk: "-", hargaEcer: "6.000", hargaPack: "-", keterangan: "-" },
    { nama: "Nota", tipe: "1ply/Kecil", ukuran: "-", merk: "-", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Nota", tipe: "2ply/Kecil", ukuran: "-", merk: "-", hargaEcer: "4.000", hargaPack: "-", keterangan: "-" },
    { nama: "Nota", tipe: "1ply/Kecil", ukuran: "-", merk: "-", hargaEcer: "6.000", hargaPack: "-", keterangan: "-" },
    { nama: "Pepak", tipe: "-", ukuran: "-", merk: "-", hargaEcer: "15.000", hargaPack: "-", keterangan: "-" },
    { nama: "Tabungan", tipe: "-", ukuran: "-", merk: "-", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Buku", tipe: "Penggalang", ukuran: "-", merk: "-", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Buku", tipe: "Penegak", ukuran: "-", merk: "-", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Buku", tipe: "Golongan", ukuran: "-", merk: "-", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Buku", tipe: "Saku Pramuka", ukuran: "-", merk: "-", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Buku", tipe: "UUD 1945", ukuran: "-", merk: "-", hargaEcer: "3.500", hargaPack: "-", keterangan: "-" },
    { nama: "Hasduk", tipe: "Merah Putih", ukuran: "-", merk: "-", hargaEcer: "15.000", hargaPack: "-", keterangan: "-" },
    { nama: "Peluit", tipe: "Plastik", ukuran: "-", merk: "-", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Peluit", tipe: "Besi", ukuran: "-", merk: "-", hargaEcer: "9.000", hargaPack: "-", keterangan: "-" },
    { nama: "Pin", tipe: "Garuda", ukuran: "-", merk: "-", hargaEcer: "7.000", hargaPack: "-", keterangan: "-" },
    { nama: "Pin", tipe: "Korpri", ukuran: "-", merk: "-", hargaEcer: "7.000", hargaPack: "-", keterangan: "-" },
    { nama: "Pin", tipe: "Merah Putih", ukuran: "-", merk: "-", hargaEcer: "5.000", hargaPack: "-", keterangan: "-" },
    { nama: "Pin Baret", tipe: "Kotak/Besi", ukuran: "-", merk: "-", hargaEcer: "7.000", hargaPack: "-", keterangan: "-" },
    { nama: "Pin Baret", tipe: "Kotak/Plastik/Merah, Kuning, Hijau", ukuran: "-", merk: "-", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Pin Baret", tipe: "Bulat/Plastik/Merah, Kuning, Hijau", ukuran: "-", merk: "-", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Ring Hasduk", tipe: "Rotan", ukuran: "-", merk: "-", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Ring Hasduk", tipe: "Plastik/Merah, Hijau", ukuran: "-", merk: "-", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Simapur", tipe: "Tongkat", ukuran: "-", merk: "-", hargaEcer: "6.000", hargaPack: "-", keterangan: "-" },
    { nama: "Simapur", tipe: "Bendera", ukuran: "-", merk: "-", hargaEcer: "6.000", hargaPack: "-", keterangan: "-" },
    { nama: "Tali Kur", tipe: "Kuning, Merah, Hijau", ukuran: "-", merk: "-", hargaEcer: "9.000", hargaPack: "-", keterangan: "-" },
    { nama: "Tali Kur", tipe: "Panjang/Hitam", ukuran: "-", merk: "-", hargaEcer: "12.000", hargaPack: "-", keterangan: "-" },
    { nama: "Tali Marlon", tipe: "Putih", ukuran: "-", merk: "-", hargaEcer: "7.000", hargaPack: "-", keterangan: "-" },
    { nama: "Tali Marlon", tipe: "Putih", ukuran: "-", merk: "-", hargaEcer: "10.000", hargaPack: "-", keterangan: "-" },
    { nama: "Tali Rami", tipe: "Kecil", ukuran: "-", merk: "-", hargaEcer: "5.000", hargaPack: "-", keterangan: "-" },
    { nama: "Tali Rami", tipe: "Besar", ukuran: "-", merk: "-", hargaEcer: "10.000", hargaPack: "-", keterangan: "-" },
    { nama: "Tongkat Pramuka", tipe: "-", ukuran: "-", merk: "-", hargaEcer: "12.000", hargaPack: "-", keterangan: "-" },
    { nama: "Topi Pramuka", tipe: "-", ukuran: "-", merk: "-", hargaEcer: "15.000", hargaPack: "-", keterangan: "-" },
    { nama: "Print Hitam Putih", tipe: "A4/HVS", ukuran: "-", merk: "-", hargaEcer: "500", hargaPack: "-", keterangan: "-" },
    { nama: "Print Hitam Putih", tipe: "A4/Buffallo", ukuran: "-", merk: "-", hargaEcer: "1.500", hargaPack: "-", keterangan: "-" },
    { nama: "Print Hitam Putih", tipe: "A4/Glossy", ukuran: "-", merk: "-", hargaEcer: "4.000", hargaPack: "-", keterangan: "-" },
    { nama: "Print Hitam Putih", tipe: "A4/Sticker", ukuran: "-", merk: "-", hargaEcer: "5.000", hargaPack: "-", keterangan: "-" },
    { nama: "Print Hitam Putih", tipe: "F4/HVS", ukuran: "-", merk: "-", hargaEcer: "500", hargaPack: "-", keterangan: "-" },
    { nama: "Print Hitam Putih", tipe: "F4/Buffallo", ukuran: "-", merk: "-", hargaEcer: "1.500", hargaPack: "-", keterangan: "-" },
    { nama: "Print Hitam Putih", tipe: "F5/Linen", ukuran: "-", merk: "-", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Print Hitam Putih", tipe: "F4/Sticker (HVs)", ukuran: "-", merk: "-", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Print Hitam Putih", tipe: "A3/HVS", ukuran: "-", merk: "-", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Print Hitam Putih", tipe: "A3/Glossy", ukuran: "-", merk: "-", hargaEcer: "6.500", hargaPack: "-", keterangan: "-" },
    { nama: "Print Hitam Putih", tipe: "A3/Sticker", ukuran: "-", merk: "-", hargaEcer: "9.500", hargaPack: "-", keterangan: "-" },
    { nama: "Print Hitam Putih", tipe: "A3+/Glossy", ukuran: "-", merk: "-", hargaEcer: "10.000", hargaPack: "-", keterangan: "-" },
    { nama: "Print 2 Sisi", tipe: "A4/HVS", ukuran: "-", merk: "-", hargaEcer: "Harga Biasa x2", hargaPack: "-", keterangan: "-" },
    { nama: "Print 2 Sisi", tipe: "A4/Buffallo", ukuran: "-", merk: "-", hargaEcer: "Harga Biasa x2", hargaPack: "-", keterangan: "-" },
    { nama: "Print 2 Sisi", tipe: "A4/Glossy", ukuran: "-", merk: "-", hargaEcer: "Harga Biasa x2", hargaPack: "-", keterangan: "-" },
    { nama: "Print 2 Sisi", tipe: "A4/Sticker", ukuran: "-", merk: "-", hargaEcer: "Harga Biasa x2", hargaPack: "-", keterangan: "-" },
    { nama: "Print 2 Sisi", tipe: "F4/HVS", ukuran: "-", merk: "-", hargaEcer: "Harga Biasa x2", hargaPack: "-", keterangan: "-" },
    { nama: "Print 2 Sisi", tipe: "F4/Buffallo", ukuran: "-", merk: "-", hargaEcer: "Harga Biasa x2", hargaPack: "-", keterangan: "-" },
    { nama: "Print 2 Sisi", tipe: "F5/Linen", ukuran: "-", merk: "-", hargaEcer: "Harga Biasa x2", hargaPack: "-", keterangan: "-" },
    { nama: "Print 2 Sisi", tipe: "F4/Sticker (HVs)", ukuran: "-", merk: "-", hargaEcer: "Harga Biasa x2", hargaPack: "-", keterangan: "-" },
    { nama: "Print 2 Sisi", tipe: "A3/HVS", ukuran: "-", merk: "-", hargaEcer: "Harga Biasa x2", hargaPack: "-", keterangan: "-" },
    { nama: "Print Warna", tipe: "A4/HVS", ukuran: "-", merk: "-", hargaEcer: "1.000", hargaPack: "-", keterangan: "-" },
    { nama: "Print Warna", tipe: "A4/Buffallo", ukuran: "-", merk: "-", hargaEcer: "2.500", hargaPack: "-", keterangan: "-" },
    { nama: "Print Warna", tipe: "A4/Glossy", ukuran: "-", merk: "-", hargaEcer: "5.000", hargaPack: "-", keterangan: "-" },
    { nama: "Print Warna", tipe: "A4/Sticker", ukuran: "-", merk: "-", hargaEcer: "6.000", hargaPack: "-", keterangan: "-" },
    { nama: "Print Warna", tipe: "F4/HVS", ukuran: "-", merk: "-", hargaEcer: "1.000", hargaPack: "-", keterangan: "-" },
    { nama: "Print Warna", tipe: "F4/Buffallo", ukuran: "-", merk: "-", hargaEcer: "2.500", hargaPack: "-", keterangan: "-" },
    { nama: "Print Warna", tipe: "F5/Linen", ukuran: "-", merk: "-", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Print Warna", tipe: "F4/Sticker (HVs)", ukuran: "-", merk: "-", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Print Warna", tipe: "A3/HVS", ukuran: "-", merk: "-", hargaEcer: "5.000", hargaPack: "-", keterangan: "-" },
    { nama: "Print Warna", tipe: "A3/Glossy", ukuran: "-", merk: "-", hargaEcer: "6.000", hargaPack: "-", keterangan: "-" },
    { nama: "Print Warna", tipe: "A3/Sticker", ukuran: "-", merk: "-", hargaEcer: "10.000", hargaPack: "-", keterangan: "-" },
    { nama: "Print Warna", tipe: "A3+/Glossy", ukuran: "-", merk: "-", hargaEcer: "7.000", hargaPack: "-", keterangan: "-" },
    { nama: "Print Warna", tipe: "A3/Sticker(Bontax)", ukuran: "-", merk: "-", hargaEcer: "7.000", hargaPack: "-", keterangan: "-" },
    { nama: "Print", tipe: "A3/Sticker(Bontax)", ukuran: "-", merk: "-", hargaEcer: "6.000", hargaPack: "-", keterangan: "-" },
    { nama: "Print", tipe: "A3/Sticker + Cutting", ukuran: "-", merk: "-", hargaEcer: "20.000", hargaPack: "-", keterangan: "-" },
    { nama: "Print", tipe: "A3/Vinyl", ukuran: "-", merk: "-", hargaEcer: "15.000", hargaPack: "-", keterangan: "-" },
    { nama: "Print Foto", tipe: "2x3/9 Lembar/Silky/Doff", ukuran: "-", merk: "Silky/Doff", hargaEcer: "5.000", hargaPack: "-", keterangan: "Ecer 1.000" },
    { nama: "Print Foto", tipe: "3x4/6 Lembar/Silky/Doff", ukuran: "-", merk: "Silky/Doff", hargaEcer: "5.000", hargaPack: "-", keterangan: "Ecer 1.500" },
    { nama: "Print Foto", tipe: "4x6/4 Lembar/Silky/Doff", ukuran: "-", merk: "Silky/Doff", hargaEcer: "5.000", hargaPack: "-", keterangan: "Ecer 1.500" },
    { nama: "Print Foto", tipe: "2R/Silky/Doff", ukuran: "-", merk: "Silky/Doff", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Print Foto", tipe: "3R/Silky/Doff", ukuran: "-", merk: "Silky/Doff", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Print Foto", tipe: "4R/Silky/Doff", ukuran: "-", merk: "Silky/Doff", hargaEcer: "4.000", hargaPack: "-", keterangan: "-" },
    { nama: "Print Foto", tipe: "5R/Silky/Doff", ukuran: "-", merk: "Silky/Doff", hargaEcer: "6.000", hargaPack: "-", keterangan: "-" },
    { nama: "Print Foto", tipe: "8R/Silky/Doff", ukuran: "-", merk: "Silky/Doff", hargaEcer: "12.000", hargaPack: "-", keterangan: "-" },
    { nama: "Print Foto", tipe: "10R/Silky/Doff", ukuran: "-", merk: "Silky/Doff", hargaEcer: "25.000", hargaPack: "-", keterangan: "-" },
    { nama: "Print Foto", tipe: "12R/Silky/Doff", ukuran: "-", merk: "Silky/Doff", hargaEcer: "35.000", hargaPack: "-", keterangan: "-" },
    { nama: "Fotocopy Satu Sisi", tipe: "A4/F4", ukuran: "-", merk: "HVS/Satu sisi", hargaEcer: "250", hargaPack: "-", keterangan: "-" },
    { nama: "Fotocopy Satu Sisi", tipe: "A3", ukuran: "-", merk: "HVS/Satu sisi", hargaEcer: "1.000", hargaPack: "-", keterangan: "-" },
    { nama: "Fotocopy Satu Sisi", tipe: "1-6/A4", ukuran: "-", merk: "HVS/Satu sisi", hargaEcer: "1.000", hargaPack: "-", keterangan: "-" },
    { nama: "Fotocopy Satu Sisi", tipe: "7-10/F4", ukuran: "-", merk: "HVS/Satu sisi", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Fotocopy Dua Sisi", tipe: "A4/F4", ukuran: "-", merk: "HVS/Dua sisi", hargaEcer: "400", hargaPack: "-", keterangan: "-" },
    { nama: "Fotocopy Dua Sisi", tipe: "A3", ukuran: "-", merk: "HVS/Dua sisi", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Fotocopy Dua Sisi", tipe: "1-6/A4", ukuran: "-", merk: "HVS/Dua sisi", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Fotocopy Dua Sisi", tipe: "7-10/F4", ukuran: "-", merk: "HVS/Dua sisi", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Scan", tipe: "A4", ukuran: "-", merk: "-", hargaEcer: "1.000", hargaPack: "-", keterangan: "-" },
    { nama: "Scan", tipe: "F4", ukuran: "-", merk: "-", hargaEcer: "1.500", hargaPack: "-", keterangan: "-" },
    { nama: "Kirim File/Save File", tipe: "A4/F4", ukuran: "-", merk: "-", hargaEcer: "1.000", hargaPack: "-", keterangan: "-" },
    { nama: "Laminating", tipe: "KTP", ukuran: "-", merk: "-", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Laminating", tipe: "A4/F4", ukuran: "-", merk: "-", hargaEcer: "5.000", hargaPack: "-", keterangan: "-" },
    { nama: "Laminating", tipe: "A3", ukuran: "-", merk: "-", hargaEcer: "10.000", hargaPack: "-", keterangan: "-" },
    { nama: "Press Mika", tipe: "-", ukuran: "-", merk: "-", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Laminasi", tipe: "-", ukuran: "-", merk: "-", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Edit", tipe: "Mudah", ukuran: "-", merk: "-", hargaEcer: "2.000", hargaPack: "-", keterangan: "-" },
    { nama: "Edit", tipe: "Sedang", ukuran: "-", merk: "-", hargaEcer: "3.000", hargaPack: "-", keterangan: "-" },
    { nama: "Edit", tipe: "Sulit", ukuran: "-", merk: "-", hargaEcer: "5.000", hargaPack: "-", keterangan: "-" },
    { nama: "Pengetikan", tipe: "A4", ukuran: "-", merk: "-", hargaEcer: "5.000", hargaPack: "-", keterangan: "-" },
    { nama: "Pengetikan", tipe: "F4", ukuran: "-", merk: "-", hargaEcer: "7.000", hargaPack: "-", keterangan: "-" },
    { nama: "Pengetikan Express", tipe: "A4", ukuran: "-", merk: "-", hargaEcer: "7.000", hargaPack: "-", keterangan: "Kondisional" },
    { nama: "Pengetikan Express", tipe: "F4", ukuran: "-", merk: "-", hargaEcer: "9.000", hargaPack: "-", keterangan: "Kondisional" },
    { nama: "Jilid Spiral", tipe: "Kecil", ukuran: "-", merk: "-", hargaEcer: "7.000", hargaPack: "-", keterangan: "-" },
    { nama: "Jilid Spiral", tipe: "Sedang", ukuran: "-", merk: "-", hargaEcer: "10.000", hargaPack: "-", keterangan: "-" },
    { nama: "Jilid Spiral", tipe: "Besar", ukuran: "-", merk: "-", hargaEcer: "15.000", hargaPack: "-", keterangan: "-" },
    { nama: "Jilid Regular", tipe: "A4/F4", ukuran: "-", merk: "-", hargaEcer: "3.000", hargaPack: "-", keterangan: "Staples + Lakban" },
    { nama: "Jilid Premium", tipe: "A4/F4", ukuran: "-", merk: "-", hargaEcer: "5.000", hargaPack: "-", keterangan: "Mika + Buffallo" },
    { nama: "Jilid Soft Cover", tipe: "-", ukuran: "-", merk: "-", hargaEcer: "25.000", hargaPack: "-", keterangan: "Proses 1-2 Hari" },
    { nama: "Jilid Hard Cover", tipe: "-", ukuran: "-", merk: "-", hargaEcer: "35.000", hargaPack: "-", keterangan: "Proses 1-2 Hari" },
    { nama: "Id card/custom", tipe: "-", ukuran: "-", merk: "-", hargaEcer: "10.000", hargaPack: "-", keterangan: "Belum termasuk Desain" },
    { nama: "Name Tag", tipe: "Biasa", ukuran: "-", merk: "-", hargaEcer: "7.000", hargaPack: "-", keterangan: "Custom" },
    { nama: "Name Tag", tipe: "Resin/Kemiti", ukuran: "-", merk: "-", hargaEcer: "20.000", hargaPack: "-", keterangan: "-" },
    { nama: "Name Tag", tipe: "Magnet", ukuran: "-", merk: "-", hargaEcer: "35.000", hargaPack: "-", keterangan: "-" },
    { nama: "Stempel Kayu", tipe: "Semua Ukuran", ukuran: "-", merk: "-", hargaEcer: "50.000", hargaPack: "-", keterangan: "desain tidak sulit" },
    { nama: "Stempel Flash", tipe: "Pricelist+20,000", ukuran: "-", merk: "Free Dsain", hargaEcer: "-", hargaPack: "-", keterangan: "desain tidak sulit" },
    { nama: "Stempel Flash", tipe: "Pricelist+20,000", ukuran: "-", merk: "Ada Dsain - 5.000", hargaEcer: "-", hargaPack: "-", keterangan: "-" },
    { nama: "Label Nama", tipe: "Sticker/A4/Isi 17", ukuran: "-", merk: "-", hargaEcer: "7.000", hargaPack: "-", keterangan: "Desain+Cutting" }
];