const dataBarang = [
  { namaBarang: "HVS 75gsm", typeUkuranWarna: "Putih/A4", merk: "All", hargaEcer: 250, hargaPack: 50000, isiPack: null },
  { namaBarang: "HVS 75gsm", typeUkuranWarna: "Putih/F4", merk: "All", hargaEcer: 250, hargaPack: 50000, isiPack: null },
  { namaBarang: "HVS 75gsm", typeUkuranWarna: "Warna/A4", merk: "All", hargaEcer: 500, hargaPack: null, isiPack: null },
  { namaBarang: "HVS 75gsm", typeUkuranWarna: "Warna/F4", merk: "All", hargaEcer: 500, hargaPack: null, isiPack: null },
  { namaBarang: "HVS 75gsm", typeUkuranWarna: "Putih/A3", merk: "All", hargaEcer: 1000, hargaPack: null, isiPack: null },
  { namaBarang: "HVS 75gsm", typeUkuranWarna: "Putih/A5", merk: "All", hargaEcer: 500, hargaPack: null, isiPack: null },
  { namaBarang: "Sticker", typeUkuranWarna: "Glossy/A4", merk: "All", hargaEcer: 3000, hargaPack: null, isiPack: null },
  { namaBarang: "Sticker", typeUkuranWarna: "Glossy/A3", merk: "All", hargaEcer: 5000, hargaPack: null, isiPack: null },
  { namaBarang: "Sticker", typeUkuranWarna: "Bontax/A4", merk: "All", hargaEcer: 2500, hargaPack: null, isiPack: null },
  { namaBarang: "Sticker", typeUkuranWarna: "Bontax/A3", merk: "All", hargaEcer: 6000, hargaPack: null, isiPack: null },
  { namaBarang: "Photo Paper", typeUkuranWarna: "Silky/Doff/A4", merk: "All", hargaEcer: 3000, hargaPack: null, isiPack: null },
  { namaBarang: "Art Paper", typeUkuranWarna: "Glossy/A4", merk: "All", hargaEcer: 4000, hargaPack: null, isiPack: null },
  { namaBarang: "Art Paper", typeUkuranWarna: "Glossy/A3", merk: "All", hargaEcer: 3000, hargaPack: null, isiPack: null },
  { namaBarang: "Art Paper", typeUkuranWarna: "Glossy/A3+", merk: "All", hargaEcer: 5000, hargaPack: null, isiPack: null },
  { namaBarang: "Buffallo", typeUkuranWarna: "1-3 Lembar", merk: "All", hargaEcer: 1000, hargaPack: 32000, isiPack: 100 },
  { namaBarang: "Buffallo", typeUkuranWarna: "4-10 Lembar", merk: "All", hargaEcer: 700, hargaPack: 32000, isiPack: 100 },
  { namaBarang: "Kado", typeUkuranWarna: "Kado/Kecil", merk: "All", hargaEcer: 2500, hargaPack: null, isiPack: null },
  { namaBarang: "Kado", typeUkuranWarna: "Kado/Besar", merk: "All", hargaEcer: 5000, hargaPack: null, isiPack: null },
  { namaBarang: "Karton", typeUkuranWarna: "Tebal", merk: "All", hargaEcer: 10000, hargaPack: null, isiPack: null },
  { namaBarang: "Karton", typeUkuranWarna: "Tipis", merk: "All", hargaEcer: 5000, hargaPack: null, isiPack: null },
  { namaBarang: "Kertas", typeUkuranWarna: "Asturo", merk: "All", hargaEcer: 5000, hargaPack: null, isiPack: null },
  { namaBarang: "Kertas", typeUkuranWarna: "Buram", merk: "All", hargaEcer: 1000, hargaPack: null, isiPack: null },
  { namaBarang: "Kertas", typeUkuranWarna: "Folio Bergaris/F4", merk: "All", hargaEcer: 500, hargaPack: null, isiPack: null },
  { namaBarang: "Kertas", typeUkuranWarna: "Kalkir", merk: "All", hargaEcer: 1500, hargaPack: null, isiPack: null },
  { namaBarang: "Kertas", typeUkuranWarna: "Karbon", merk: "All", hargaEcer: 1000, hargaPack: null, isiPack: null },
  { namaBarang: "Kertas", typeUkuranWarna: "Kilap", merk: "All", hargaEcer: 2500, hargaPack: null, isiPack: null },
  { namaBarang: "Kertas", typeUkuranWarna: "Linen", merk: "All", hargaEcer: 2000, hargaPack: null, isiPack: null },
  { namaBarang: "Kertas", typeUkuranWarna: "Manila/Hitam, Merah, Ungu, Coklat", merk: "All", hargaEcer: 4000, hargaPack: null, isiPack: null },
  { namaBarang: "Kertas", typeUkuranWarna: "Manila/Putih, Kuning, Biru Muda, Hijau Muda", merk: "All", hargaEcer: 3000, hargaPack: null, isiPack: null },
  { namaBarang: "Kertas", typeUkuranWarna: "Sukun", merk: "All", hargaEcer: 2500, hargaPack: null, isiPack: null },
  { namaBarang: "Kwitansi", typeUkuranWarna: "Kecil", merk: "All", hargaEcer: 4000, hargaPack: null, isiPack: null },
  { namaBarang: "Kwitansi", typeUkuranWarna: "Besar", merk: "All", hargaEcer: 5500, hargaPack: null, isiPack: null },
  { namaBarang: "Label Harga", typeUkuranWarna: "-", merk: "All", hargaEcer: 1000, hargaPack: null, isiPack: null },
  { namaBarang: "Map", typeUkuranWarna: "Snail", merk: "All", hargaEcer: 4000, hargaPack: null, isiPack: null },
  { namaBarang: "Map", typeUkuranWarna: "Kancing", merk: "All", hargaEcer: 4000, hargaPack: null, isiPack: null },
  { namaBarang: "Map", typeUkuranWarna: "L", merk: "All", hargaEcer: 3000, hargaPack: 20000, isiPack: null },
  { namaBarang: "Map", typeUkuranWarna: "Kertas", merk: "All", hargaEcer: 2000, hargaPack: 52000, isiPack: 50 },
  { namaBarang: "Map", typeUkuranWarna: "Diamond", merk: "All", hargaEcer: 5000, hargaPack: null, isiPack: null },
  { namaBarang: "Mika", typeUkuranWarna: "Laminating/A4", merk: "All", hargaEcer: 5000, hargaPack: null, isiPack: null },
  { namaBarang: "Mika", typeUkuranWarna: "Laminating/A3", merk: "All", hargaEcer: 10000, hargaPack: null, isiPack: null },
  { namaBarang: "Mika Jilid", typeUkuranWarna: "A4", merk: "All", hargaEcer: 2000, hargaPack: null, isiPack: null },
  { namaBarang: "Mika Jilid", typeUkuranWarna: "F4/Warna", merk: "All", hargaEcer: 2000, hargaPack: null, isiPack: null },
  { namaBarang: "Nota", typeUkuranWarna: "1ply/Kecil", merk: "All", hargaEcer: 3000, hargaPack: null, isiPack: null },
  { namaBarang: "Nota", typeUkuranWarna: "2ply/Kecil", merk: "All", hargaEcer: 4000, hargaPack: null, isiPack: null },
  { namaBarang: "Origami", typeUkuranWarna: "14x14cm", merk: "All", hargaEcer: 4000, hargaPack: null, isiPack: null },
  { namaBarang: "Origami", typeUkuranWarna: "Craft 14x14cm", merk: "All", hargaEcer: 5000, hargaPack: null, isiPack: null },
  { namaBarang: "Origami", typeUkuranWarna: "16x16mm", merk: "All", hargaEcer: 5000, hargaPack: null, isiPack: null },
  { namaBarang: "Origami", typeUkuranWarna: "Craft/16x16mm", merk: "All", hargaEcer: 6000, hargaPack: null, isiPack: null },
  { namaBarang: "Origami", typeUkuranWarna: "Metalic/16x16mm", merk: "All", hargaEcer: 12000, hargaPack: null, isiPack: null },
  { namaBarang: "Origami", typeUkuranWarna: "18x18cm", merk: "All", hargaEcer: 6000, hargaPack: null, isiPack: null },
  { namaBarang: "Origami", typeUkuranWarna: "20x20mm", merk: "All", hargaEcer: 6500, hargaPack: null, isiPack: null },
  { namaBarang: "Sticky Note", typeUkuranWarna: "15x50mm", merk: "Trifello", hargaEcer: 7000, hargaPack: null, isiPack: null },
  { namaBarang: "Sticky Note", typeUkuranWarna: "38x51mm", merk: "BIG", hargaEcer: 5000, hargaPack: null, isiPack: null },
  { namaBarang: "Sticky Note", typeUkuranWarna: "51x38mm", merk: "BIG", hargaEcer: 4000, hargaPack: null, isiPack: null },
  { namaBarang: "Sticky Note", typeUkuranWarna: "76x76mm", merk: "BIG", hargaEcer: 7000, hargaPack: null, isiPack: null },
  { namaBarang: "Sticky Note", typeUkuranWarna: "76x91mm", merk: "BIG", hargaEcer: null, hargaPack: null, isiPack: null },
  { namaBarang: "Sticky Note", typeUkuranWarna: "50x15mm", merk: "BIG", hargaEcer: null, hargaPack: null, isiPack: null },
  { namaBarang: "Sticky Note", typeUkuranWarna: "76x51mm", merk: "BIG", hargaEcer: 6000, hargaPack: null, isiPack: null },
  { namaBarang: "Sticky Note", typeUkuranWarna: "Transparant/76x76mm", merk: "BIG", hargaEcer: 10000, hargaPack: null, isiPack: null },
  { namaBarang: "Sticky Note", typeUkuranWarna: "Index (Pagar)", merk: "BIG", hargaEcer: 9000, hargaPack: null, isiPack: null },
  { namaBarang: "Sticky Note", typeUkuranWarna: "Motif/15x50mm", merk: "-", hargaEcer: 5000, hargaPack: null, isiPack: null },
  { namaBarang: "Map", typeUkuranWarna: "Resleting + Kancing", merk: "-", hargaEcer: 16000, hargaPack: null, isiPack: null },
  { namaBarang: "Map", typeUkuranWarna: "Full Resleting", merk: "-", hargaEcer: 13000, hargaPack: null, isiPack: null },
  { namaBarang: "Amplop", typeUkuranWarna: "Coklat/Lamaran/Garis", merk: "-", hargaEcer: 2500, hargaPack: null, isiPack: null },
  { namaBarang: "Amplop", typeUkuranWarna: "Coklat/Lamaran/Polos", merk: "-", hargaEcer: 2000, hargaPack: null, isiPack: null },
  { namaBarang: "Amplop", typeUkuranWarna: "Coklat/Dokumen/Sedang", merk: "-", hargaEcer: 1500, hargaPack: null, isiPack: null },
  { namaBarang: "Amplop", typeUkuranWarna: "Coklat/Dokumen/Kecil/Seal @3pcs", merk: "-", hargaEcer: 2000, hargaPack: null, isiPack: null },
  { namaBarang: "Amplop", typeUkuranWarna: "Coklat/Dokumen/Kecil/Non Seal", merk: "-", hargaEcer: 1000, hargaPack: null, isiPack: null },
  { namaBarang: "Amplop", typeUkuranWarna: "104/Seal/Non Booklet", merk: "PPLine", hargaEcer: 500, hargaPack: null, isiPack: null },
  { namaBarang: "Amplop", typeUkuranWarna: "110/Seal/Booklet", merk: "PPLine", hargaEcer: 500, hargaPack: null, isiPack: null },
  { namaBarang: "Amplop", typeUkuranWarna: "110/Seal/Non Booklet", merk: "PPLine", hargaEcer: 500, hargaPack: null, isiPack: null },
  { namaBarang: "Amplop", typeUkuranWarna: "110/Non Seal/Polos", merk: "B'Gain", hargaEcer: 250, hargaPack: null, isiPack: null },
  { namaBarang: "Amplop", typeUkuranWarna: "Besar", merk: "Merpati", hargaEcer: 500, hargaPack: null, isiPack: null }
];