const dataBarang = [
  { no: 1, namaBarang: "Buku", typeUkuranWarna: "Penggalang", merk: "-", hargaEcer: 3000, hargaPack: null },
  { no: 2, namaBarang: "Buku", typeUkuranWarna: "Penegak", merk: "-", hargaEcer: 3000, hargaPack: null },
  { no: 3, namaBarang: "Buku", typeUkuranWarna: "Golongan", merk: "-", hargaEcer: 3000, hargaPack: null },
  { no: 4, namaBarang: "Buku", typeUkuranWarna: "Saku Pramuka", merk: "-", hargaEcer: 3000, hargaPack: null },
  { no: 5, namaBarang: "Buku", typeUkuranWarna: "UUD 1945", merk: "-", hargaEcer: 3500, hargaPack: null },
  { no: 6, namaBarang: "Hasduk", typeUkuranWarna: "Merah Putih", merk: "-", hargaEcer: 15000, hargaPack: null },
  { no: 7, namaBarang: "Peluit", typeUkuranWarna: "Plastik", merk: "-", hargaEcer: 3000, hargaPack: null },
  { no: 8, namaBarang: "Peluit", typeUkuranWarna: "Besi", merk: "-", hargaEcer: 9000, hargaPack: null },
  { no: 9, namaBarang: "Pin", typeUkuranWarna: "Garuda", merk: "-", hargaEcer: 7000, hargaPack: null },
  { no: 10, namaBarang: "Pin", typeUkuranWarna: "Korpri", merk: "-", hargaEcer: 7000, hargaPack: null },
  { no: 11, namaBarang: "Pin", typeUkuranWarna: "Merah Putih", merk: "-", hargaEcer: 5000, hargaPack: null },
  { no: 12, namaBarang: "Pin Baret", typeUkuranWarna: "Kotak/Besi", merk: "-", hargaEcer: 7000, hargaPack: null },
  { no: 13, namaBarang: "Pin Baret", typeUkuranWarna: "Kotak/Plastik/Merah, Kuning, Hijau", merk: "-", hargaEcer: 2000, hargaPack: null },
  { no: 14, namaBarang: "Pin Baret", typeUkuranWarna: "Bulat/Plastik/Merah, Kuning, Hijau", merk: "-", hargaEcer: 2000, hargaPack: null },
  { no: 15, namaBarang: "Ring Hasduk", typeUkuranWarna: "Rotan", merk: "-", hargaEcer: 2000, hargaPack: null },
  { no: 16, namaBarang: "Ring Hasduk", typeUkuranWarna: "Plastik/Merah, Hijau", merk: "-", hargaEcer: 2000, hargaPack: null },
  { no: 17, namaBarang: "Simapur", typeUkuranWarna: "Tongkat", merk: "-", hargaEcer: 6000, hargaPack: null },
  { no: 18, namaBarang: "Simapur", typeUkuranWarna: "Bendera", merk: "-", hargaEcer: 6000, hargaPack: null },
  { no: 19, namaBarang: "Tali Kur", typeUkuranWarna: "Kuning, Merah, Hijau", merk: "-", hargaEcer: 9000, hargaPack: null },
  { no: 20, namaBarang: "Tali Kur", typeUkuranWarna: "Panjang/Hitam", merk: "-", hargaEcer: 12000, hargaPack: null },
  { no: 21, namaBarang: "Tali Marlon", typeUkuranWarna: "Putih", merk: "-", hargaEcer: 7000, hargaPack: null },
  { no: 22, namaBarang: "Tali Marlon", typeUkuranWarna: "Putih", merk: "-", hargaEcer: 10000, hargaPack: null },
  { no: 23, namaBarang: "Tali Rami", typeUkuranWarna: "Kecil", merk: "-", hargaEcer: 5000, hargaPack: null },
  { no: 24, namaBarang: "Tali Rami", typeUkuranWarna: "Besar", merk: "-", hargaEcer: 10000, hargaPack: null },
  { no: 25, namaBarang: "Tongkat Pramuka", typeUkuranWarna: "-", merk: "-", hargaEcer: 12000, hargaPack: null },
  { no: 26, namaBarang: "Topi Pramuka", typeUkuranWarna: "-", merk: "-", hargaEcer: 15000, hargaPack: null }
];