const dataBarang = [
  { no: 1, namaBarang: "Bolpoin", typeUkuranWarna: "Warna/Hitam", merk: "Apel", hargaEcer: 3000, hargaPack: null },
  { no: 2, namaBarang: "Bolpoin", typeUkuranWarna: "Softline 1900", merk: "Artline", hargaEcer: 10000, hargaPack: null },
  { no: 3, namaBarang: "Bolpoin", typeUkuranWarna: "-", merk: "Bolpenku", hargaEcer: 1000, hargaPack: null },
  { no: 4, namaBarang: "Bolpoin", typeUkuranWarna: "C600", merk: "Faster", hargaEcer: 3000, hargaPack: null },
  { no: 5, namaBarang: "Bolpoin", typeUkuranWarna: "F3", merk: "Faster", hargaEcer: 3000, hargaPack: null },
  { no: 6, namaBarang: "Bolpoin", typeUkuranWarna: "C6", merk: "Faster", hargaEcer: 4000, hargaPack: null },
  { no: 7, namaBarang: "Bolpoin", typeUkuranWarna: "HS866", merk: "Hi-Tech", hargaEcer: 4000, hargaPack: null },
  { no: 8, namaBarang: "Bolpoin", typeUkuranWarna: "JK-100", merk: "Joyko", hargaEcer: 3000, hargaPack: null },
  { no: 9, namaBarang: "Bolpoin", typeUkuranWarna: "GP243", merk: "Joyko", hargaEcer: 4000, hargaPack: null },
  { no: 10, namaBarang: "Bolpoin", typeUkuranWarna: "BP 199", merk: "Joyko", hargaEcer: 5000, hargaPack: null },
  { no: 11, namaBarang: "Bolpoin", typeUkuranWarna: "GPC299", merk: "Joyko", hargaEcer: 4000, hargaPack: null },
  { no: 12, namaBarang: "Bolpoin", typeUkuranWarna: "K-200", merk: "Kenko", hargaEcer: 3000, hargaPack: null },
  { no: 13, namaBarang: "Bolpoin", typeUkuranWarna: "K-1", merk: "Kenko", hargaEcer: 3000, hargaPack: null },
  { no: 14, namaBarang: "Bolpoin", typeUkuranWarna: "Warna/Hitam", merk: "Kokoro", hargaEcer: 7000, hargaPack: null },
  { no: 15, namaBarang: "Bolpoin", typeUkuranWarna: "Warna/Hitam/BPTP", merk: "Pilot", hargaEcer: 3000, hargaPack: null },
  { no: 16, namaBarang: "Bolpoin", typeUkuranWarna: "Picolo", merk: "Zebra", hargaEcer: 3000, hargaPack: null },
  { no: 17, namaBarang: "Bolpoin", typeUkuranWarna: "-", merk: "Pororo", hargaEcer: 5000, hargaPack: null },
  { no: 18, namaBarang: "Bolpoin", typeUkuranWarna: "S1", merk: "Snowman", hargaEcer: 3000, hargaPack: null },
  { no: 19, namaBarang: "Bolpoin", typeUkuranWarna: "V3", merk: "Snowman", hargaEcer: 4000, hargaPack: null },
  { no: 20, namaBarang: "Bolpoin", typeUkuranWarna: "Vision 2", merk: "Snowman", hargaEcer: 3000, hargaPack: null },
  { no: 21, namaBarang: "Bolpoin", typeUkuranWarna: "Warna/Polos/AE7", merk: "Standard", hargaEcer: 3000, hargaPack: null },
  { no: 22, namaBarang: "Bolpoin", typeUkuranWarna: "P5", merk: "Standard", hargaEcer: 4000, hargaPack: null },
  { no: 23, namaBarang: "Bolpoin", typeUkuranWarna: "B'Live", merk: "Standard", hargaEcer: 4000, hargaPack: null },
  { no: 24, namaBarang: "Bolpoin", typeUkuranWarna: "Warna/Polos", merk: "Weiyada", hargaEcer: 6000, hargaPack: null },
  { no: 25, namaBarang: "Bolpoin", typeUkuranWarna: "Penciltic", merk: "Zebra", hargaEcer: 6000, hargaPack: null },
  { no: 26, namaBarang: "Bolpoin", typeUkuranWarna: "C6000", merk: "Queens", hargaEcer: 2000, hargaPack: null },
  { no: 27, namaBarang: "Isi Bolpoin", typeUkuranWarna: "-", merk: "-", hargaEcer: null, hargaPack: null },
  { no: 28, namaBarang: "Pensil", typeUkuranWarna: "HB", merk: "Staedtler", hargaEcer: 5000, hargaPack: null },
  { no: 29, namaBarang: "Pensil", typeUkuranWarna: "Platinum 5000", merk: "Benefit", hargaEcer: 2000, hargaPack: null },
  { no: 30, namaBarang: "Pensil", typeUkuranWarna: "2B", merk: "Faber-Castell", hargaEcer: 5000, hargaPack: null },
  { no: 31, namaBarang: "Pensil", typeUkuranWarna: "4B - 8B", merk: "Faber-Castell", hargaEcer: 6000, hargaPack: null },
  { no: 32, namaBarang: "Pensil", typeUkuranWarna: "2B", merk: "Greebel", hargaEcer: 2500, hargaPack: null },
  { no: 33, namaBarang: "Pensil", typeUkuranWarna: "P-93", merk: "Joyko", hargaEcer: 2000, hargaPack: null },
  { no: 34, namaBarang: "Pensil", typeUkuranWarna: "0810", merk: "Kenko", hargaEcer: 2000, hargaPack: null },
  { no: 35, namaBarang: "Pensil", typeUkuranWarna: "TF 6388", merk: "Trifelo", hargaEcer: 2000, hargaPack: null },
  { no: 36, namaBarang: "Pensil Mekanik", typeUkuranWarna: "MP-7013", merk: "Benefit", hargaEcer: 6000, hargaPack: null },
  { no: 37, namaBarang: "Pensil Mekanik", typeUkuranWarna: "MP-22", merk: "Benefit", hargaEcer: 4500, hargaPack: null },
  { no: 38, namaBarang: "Pensil Mekanik", typeUkuranWarna: "BP-338", merk: "Joyko", hargaEcer: 3000, hargaPack: null },
  { no: 39, namaBarang: "Pensil Mekanik", typeUkuranWarna: "SF-202", merk: "Safari", hargaEcer: 4000, hargaPack: null },
  { no: 40, namaBarang: "Pensil Mekanik", typeUkuranWarna: "MP02", merk: "Eselon", hargaEcer: 4000, hargaPack: null },
  { no: 41, namaBarang: "Isi Pensil", typeUkuranWarna: "0,5", merk: "Joyko", hargaEcer: 3000, hargaPack: null },
  { no: 42, namaBarang: "Isi Pensil", typeUkuranWarna: "0,7", merk: "Joyko", hargaEcer: 3000, hargaPack: null },
  { no: 43, namaBarang: "Isi Pensil", typeUkuranWarna: "0,7", merk: "Faber-Castell", hargaEcer: 3000, hargaPack: null },
  { no: 44, namaBarang: "Spidol Non Permanent", typeUkuranWarna: "Kecil", merk: "Snowman", hargaEcer: 3000, hargaPack: null },
  { no: 45, namaBarang: "Spidol Non Permanent", typeUkuranWarna: "Kecil", merk: "Artline", hargaEcer: 3000, hargaPack: null },
  { no: 46, namaBarang: "Spidol Non Permanent", typeUkuranWarna: "900XF", merk: "Artline", hargaEcer: 17000, hargaPack: null },
  { no: 47, namaBarang: "Spidol Non Permanent", typeUkuranWarna: "400XF", merk: "Artline", hargaEcer: 17000, hargaPack: null },
  { no: 48, namaBarang: "Spidol Non Permanent", typeUkuranWarna: "EK-231N", merk: "Artline", hargaEcer: 11000, hargaPack: null },
  { no: 49, namaBarang: "Spidol Non Permanent", typeUkuranWarna: "990XF", merk: "Artline", hargaEcer: 15000, hargaPack: null },
  { no: 50, namaBarang: "Spidol Non Permanent", typeUkuranWarna: "Hijau", merk: "Montana", hargaEcer: 5000, hargaPack: null },
  { no: 51, namaBarang: "Spidol Non Permanent", typeUkuranWarna: "White", merk: "Snowman", hargaEcer: 17000, hargaPack: null },
  { no: 52, namaBarang: "Spidol Non Permanent", typeUkuranWarna: "FT700", merk: "Snowman", hargaEcer: 10000, hargaPack: null },
  { no: 53, namaBarang: "Spidol Non Permanent", typeUkuranWarna: "Merah", merk: "Snowman", hargaEcer: 8500, hargaPack: null },
  { no: 54, namaBarang: "Spidol Non Permanent", typeUkuranWarna: "Putih", merk: "Snowman", hargaEcer: 15000, hargaPack: null },
  { no: 55, namaBarang: "Spidol Non Permanent", typeUkuranWarna: "Hitam", merk: "Snowman", hargaEcer: 8000, hargaPack: null },
  { no: 56, namaBarang: "Spidol Non Permanent", typeUkuranWarna: "12 warna", merk: "Snowman", hargaEcer: 17000, hargaPack: null },
  { no: 57, namaBarang: "Spidol Permanent", typeUkuranWarna: "Hitam", merk: "Snowman", hargaEcer: 7000, hargaPack: null },
  { no: 58, namaBarang: "Spidol Permanent", typeUkuranWarna: "Biru", merk: "Snowman", hargaEcer: 8000, hargaPack: null },
  { no: 59, namaBarang: "Spidol Permanent", typeUkuranWarna: "Biru", merk: "Artline", hargaEcer: 8000, hargaPack: null },
  { no: 60, namaBarang: "Isi Spidol Permanent", typeUkuranWarna: "Hitam", merk: "Snowman", hargaEcer: 15000, hargaPack: null },
  { no: 61, namaBarang: "Isi Spidol Non Permanent", typeUkuranWarna: "Hitam", merk: "Snowman", hargaEcer: 18000, hargaPack: null },
  { no: 62, namaBarang: "Pensil Warna", typeUkuranWarna: "-", merk: "Joyko", hargaEcer: 8500, hargaPack: null },
  { no: 63, namaBarang: "Krayon", typeUkuranWarna: "Oil Pastels", merk: "Greebel", hargaEcer: 3000, hargaPack: null },
  { no: 64, namaBarang: "Krayon", typeUkuranWarna: "Pensil", merk: "Titi", hargaEcer: 16000, hargaPack: null }
];