const dataBarang = [
  { no: 1, namaBarang: "Bak Stempel", typeUkuranWarna: "Kecil", merk: "Joyko", hargaEcer: 7000, hargaPack: null },
  { no: 2, namaBarang: "Bak Stempel", typeUkuranWarna: "Besar", merk: "Hero", hargaEcer: 9000, hargaPack: null },
  { no: 3, namaBarang: "Busur", typeUkuranWarna: "-", merk: "No Merk", hargaEcer: 2000, hargaPack: null },
  { no: 4, namaBarang: "Busur", typeUkuranWarna: "-", merk: "Butterfly", hargaEcer: 4500, hargaPack: null },
  { no: 5, namaBarang: "Cat", typeUkuranWarna: "Warna/Kecil", merk: "Aga", hargaEcer: 10000, hargaPack: null },
  { no: 6, namaBarang: "Cat", typeUkuranWarna: "Warna/Besar", merk: "Aga", hargaEcer: 18000, hargaPack: null },
  { no: 7, namaBarang: "Cat", typeUkuranWarna: "Acrylic/12 Shades", merk: "Morning Star", hargaEcer: 16000, hargaPack: null },
  { no: 8, namaBarang: "Cat", typeUkuranWarna: "Air", merk: "Mr. Loveguitar", hargaEcer: 12000, hargaPack: null },
  { no: 9, namaBarang: "Correction Tape (Stipo)", typeUkuranWarna: "Fluid (Cair)", merk: "Joyko", hargaEcer: 5000, hargaPack: null },
  { no: 10, namaBarang: "Correction Tape (Stipo)", typeUkuranWarna: "Fluid (Cair)", merk: "Greebel", hargaEcer: 6000, hargaPack: null },
  { no: 11, namaBarang: "Correction Tape (Stipo)", typeUkuranWarna: "Kertas", merk: "Joyko", hargaEcer: 7000, hargaPack: null },
  { no: 12, namaBarang: "Correction Tape (Stipo)", typeUkuranWarna: "Kertas", merk: "Jenia, dll.", hargaEcer: 6000, hargaPack: null },
  { no: 13, namaBarang: "Cutter", typeUkuranWarna: "Mini", merk: "-", hargaEcer: 4000, hargaPack: null },
  { no: 14, namaBarang: "Cutter", typeUkuranWarna: "Kecil", merk: "Kenko", hargaEcer: 7500, hargaPack: null },
  { no: 15, namaBarang: "Cutter", typeUkuranWarna: "Besar", merk: "Kenko", hargaEcer: 14000, hargaPack: null },
  { no: 16, namaBarang: "Cutter", typeUkuranWarna: "Kecil", merk: "Safari", hargaEcer: 3000, hargaPack: null },
  { no: 17, namaBarang: "Cutter", typeUkuranWarna: "Besar", merk: "Safari", hargaEcer: 6000, hargaPack: null },
  { no: 18, namaBarang: "Double Tape", typeUkuranWarna: "Foam/Besar", merk: "Berry Tape", hargaEcer: 9000, hargaPack: null },
  { no: 19, namaBarang: "Double Tape", typeUkuranWarna: "Foam/Kecil", merk: "Nachi Tape, dll.", hargaEcer: 6000, hargaPack: null },
  { no: 20, namaBarang: "Double Tape", typeUkuranWarna: "Kecil", merk: "Nachi Tape, dll.", hargaEcer: 3000, hargaPack: null },
  { no: 21, namaBarang: "Double Tape", typeUkuranWarna: "12mm", merk: "Nachi Tape, dll.", hargaEcer: 4000, hargaPack: null },
  { no: 22, namaBarang: "Double Tape", typeUkuranWarna: "Akrilik", merk: "Trifelo", hargaEcer: 8000, hargaPack: null },
  { no: 23, namaBarang: "Double Tape", typeUkuranWarna: "Besar", merk: "Nachi Tape, dll.", hargaEcer: 12000, hargaPack: null },
  { no: 24, namaBarang: "Double Tape", typeUkuranWarna: "Sedang", merk: "Nachi Tape, dll.", hargaEcer: 6500, hargaPack: null },
  { no: 25, namaBarang: "Gabus/Sterofoam", typeUkuranWarna: "Polos", merk: "-", hargaEcer: 8000, hargaPack: null },
  { no: 26, namaBarang: "Gabus/Sterofoam", typeUkuranWarna: "Warna", merk: "-", hargaEcer: 10000, hargaPack: null },
  { no: 27, namaBarang: "Gunting", typeUkuranWarna: "Kecil", merk: "Kenko", hargaEcer: 5500, hargaPack: null },
  { no: 28, namaBarang: "Gunting", typeUkuranWarna: "Sedang", merk: "Kenko", hargaEcer: 8000, hargaPack: null },
  { no: 29, namaBarang: "Gunting", typeUkuranWarna: "Besar", merk: "Kenko", hargaEcer: 12000, hargaPack: null },
  { no: 30, namaBarang: "Gunting", typeUkuranWarna: "Kecil", merk: "Orlee/dsb.", hargaEcer: 5000, hargaPack: null },
  { no: 31, namaBarang: "Gunting", typeUkuranWarna: "Sedang", merk: "Orlee/dsb.", hargaEcer: 6000, hargaPack: null },
  { no: 32, namaBarang: "Gunting", typeUkuranWarna: "Besar", merk: "Orlee/dsb.", hargaEcer: 8000, hargaPack: null },
  { no: 33, namaBarang: "Isi Cutter", typeUkuranWarna: "Kecil", merk: "Kenko", hargaEcer: 5000, hargaPack: null },
  { no: 34, namaBarang: "Isi Cutter", typeUkuranWarna: "Besar", merk: "Kenko", hargaEcer: 6000, hargaPack: null },
  { no: 35, namaBarang: "Isi Lem Tembak", typeUkuranWarna: "-", merk: "-", hargaEcer: 1500, hargaPack: null },
  { no: 36, namaBarang: "Isi Staples", typeUkuranWarna: "5mm/kecil", merk: "Max", hargaEcer: 4000, hargaPack: null },
  { no: 37, namaBarang: "Isi Staples", typeUkuranWarna: "24/6", merk: "Etona", hargaEcer: 7000, hargaPack: null },
  { no: 38, namaBarang: "Isi Staples", typeUkuranWarna: "23/15", merk: "Etona", hargaEcer: 21000, hargaPack: null },
  { no: 39, namaBarang: "Isi Staples", typeUkuranWarna: "23/13", merk: "Etona", hargaEcer: 18000, hargaPack: null },
  { no: 40, namaBarang: "Isi Staples", typeUkuranWarna: "23/8", merk: "Etona", hargaEcer: 10000, hargaPack: null },
  { no: 41, namaBarang: "Isi Staples", typeUkuranWarna: "23/10", merk: "Etona", hargaEcer: 15000, hargaPack: null },
  { no: 42, namaBarang: "Isolasi", typeUkuranWarna: "12mm/Kecil", merk: "Borneo", hargaEcer: 2500, hargaPack: null },
  { no: 43, namaBarang: "Isolasi", typeUkuranWarna: "12mm/Kecil", merk: "Nachi Tape, dll.", hargaEcer: 2000, hargaPack: null },
  { no: 44, namaBarang: "Isolasi", typeUkuranWarna: "12mm/Besar", merk: "Nachi Tape, dll.", hargaEcer: 4000, hargaPack: null },
  { no: 45, namaBarang: "Isolasi", typeUkuranWarna: "24mm", merk: "Nachi Tape, dll.", hargaEcer: 6000, hargaPack: null },
  { no: 46, namaBarang: "Isolasi", typeUkuranWarna: "Bening/Besar", merk: "Nachi Tape, dll.", hargaEcer: 8000, hargaPack: null },
  { no: 47, namaBarang: "Isolasi", typeUkuranWarna: "Coklat/Besar", merk: "Berry Tape", hargaEcer: 10000, hargaPack: null },
  { no: 48, namaBarang: "Isolasi", typeUkuranWarna: "Kertas/Kecil", merk: "Berry Tape", hargaEcer: 3000, hargaPack: null },
  { no: 49, namaBarang: "Isolasi", typeUkuranWarna: "Kertas/Sedang", merk: "Berry Tape", hargaEcer: 5000, hargaPack: null },
  { no: 50, namaBarang: "Isolasi", typeUkuranWarna: "Kertas/Sedang", merk: "Safari", hargaEcer: 6000, hargaPack: null },
  { no: 51, namaBarang: "Isolasi", typeUkuranWarna: "Listrik/Kecil", merk: "Nachi Tape, dll.", hargaEcer: 4000, hargaPack: null },
  { no: 52, namaBarang: "Isolasi", typeUkuranWarna: "Hitam/Sedang", merk: "Nachi Tape, dll.", hargaEcer: 12000, hargaPack: null },
  { no: 53, namaBarang: "Isolasi", typeUkuranWarna: "Hitam/Besar", merk: "Nachi Tape, dll.", hargaEcer: 15000, hargaPack: null },
  { no: 54, namaBarang: "Jangka", typeUkuranWarna: "-", merk: "Joyko", hargaEcer: 10000, hargaPack: null },
  { no: 55, namaBarang: "Kalkulator", typeUkuranWarna: "Mini", merk: "-", hargaEcer: 15000, hargaPack: null },
  { no: 56, namaBarang: "Kalkulator", typeUkuranWarna: "Scientific", merk: "-", hargaEcer: 35000, hargaPack: null },
  { no: 57, namaBarang: "Kapur Papan Tulis", typeUkuranWarna: "Warna", merk: "Trisensa", hargaEcer: 12000, hargaPack: null },
  { no: 58, namaBarang: "Kapur Papan Tulis", typeUkuranWarna: "Polos", merk: "Trisensa", hargaEcer: 5000, hargaPack: null },
  { no: 59, namaBarang: "Kapur Semut", typeUkuranWarna: "-", merk: "Bagus", hargaEcer: 4000, hargaPack: null },
  { no: 60, namaBarang: "Klip Jumbo", typeUkuranWarna: "Ecer", merk: "V-Tec", hargaEcer: 1500, hargaPack: null },
  { no: 61, namaBarang: "Klip Kertas (Binder)", typeUkuranWarna: "280", merk: "BIG", hargaEcer: 5000, hargaPack: null },
  { no: 62, namaBarang: "Klip Kertas (Binder)", typeUkuranWarna: "260", merk: "BIG", hargaEcer: 3000, hargaPack: null },
  { no: 63, namaBarang: "Klip Kertas (Binder)", typeUkuranWarna: "200", merk: "BIG", hargaEcer: 2000, hargaPack: null },
  { no: 64, namaBarang: "Klip Kertas (Binder)", typeUkuranWarna: "155", merk: "BIG", hargaEcer: 2000, hargaPack: null },
  { no: 65, namaBarang: "Klip Kertas (Binder)", typeUkuranWarna: "111", merk: "BIG", hargaEcer: 1000, hargaPack: null },
  { no: 66, namaBarang: "Klip Kertas (Binder)", typeUkuranWarna: "107", merk: "BIG", hargaEcer: 1000, hargaPack: null },
  { no: 67, namaBarang: "Klip Kertas (Binder)", typeUkuranWarna: "105", merk: "BIG", hargaEcer: 1000, hargaPack: null },
  { no: 68, namaBarang: "Klip Trigonal", typeUkuranWarna: "1box Plastik", merk: "BIG", hargaEcer: 6000, hargaPack: null },
  { no: 69, namaBarang: "Klip Trigonal", typeUkuranWarna: "1box Kardus", merk: "BIG", hargaEcer: 4000, hargaPack: null },
  { no: 70, namaBarang: "Klip Trigonal", typeUkuranWarna: "1 Plastik/4pcs", merk: "-", hargaEcer: 1000, hargaPack: null },
  { no: 71, namaBarang: "Klip Vinyl", typeUkuranWarna: "Warna", merk: "ZRM", hargaEcer: 5000, hargaPack: null },
  { no: 72, namaBarang: "Kuas", typeUkuranWarna: "1 set", merk: "Vis-1", hargaEcer: 9000, hargaPack: null },
  { no: 73, namaBarang: "Kuas", typeUkuranWarna: "1 set", merk: "Combo", hargaEcer: 8000, hargaPack: null },
  { no: 74, namaBarang: "Kuas", typeUkuranWarna: "1-2", merk: "Ecer", hargaEcer: 2000, hargaPack: null },
  { no: 75, namaBarang: "Kuas", typeUkuranWarna: "3", merk: "Ecer", hargaEcer: 3000, hargaPack: null },
  { no: 76, namaBarang: "Kuas", typeUkuranWarna: "7", merk: "Ecer", hargaEcer: 4000, hargaPack: null },
  { no: 77, namaBarang: "Kuas", typeUkuranWarna: "8-9", merk: "Ecer", hargaEcer: 5000, hargaPack: null },
  { no: 78, namaBarang: "Kuas", typeUkuranWarna: "10", merk: "Ecer", hargaEcer: 6000, hargaPack: null },
  { no: 79, namaBarang: "Lem Cair", typeUkuranWarna: "Kecil", merk: "Povinal", hargaEcer: 3000, hargaPack: null },
  { no: 80, namaBarang: "Lem Cair", typeUkuranWarna: "Besar", merk: "Povinal", hargaEcer: 6000, hargaPack: null },
  { no: 81, namaBarang: "Lem Cair", typeUkuranWarna: "-", merk: "Castol", hargaEcer: 7000, hargaPack: null },
  { no: 82, namaBarang: "Lem Cair", typeUkuranWarna: "-", merk: "UHU", hargaEcer: 9000, hargaPack: null },
  { no: 83, namaBarang: "Lem Cair", typeUkuranWarna: "-", merk: "Alteco", hargaEcer: 5500, hargaPack: null },
  { no: 84, namaBarang: "Lem Cair", typeUkuranWarna: "Kecil", merk: "Fox", hargaEcer: 11000, hargaPack: null },
  { no: 85, namaBarang: "Lem Cair", typeUkuranWarna: "Besar", merk: "Fox", hargaEcer: 11000, hargaPack: null },
  { no: 86, namaBarang: "Lem Cair", typeUkuranWarna: "-", merk: "Greebel", hargaEcer: 6000, hargaPack: null },
  { no: 87, namaBarang: "Lem G", typeUkuranWarna: "-", merk: "G", hargaEcer: 7000, hargaPack: null },
  { no: 88, namaBarang: "Lem Stick", typeUkuranWarna: "Kecil", merk: "Joyko", hargaEcer: 3000, hargaPack: null },
  { no: 89, namaBarang: "Lem Stick", typeUkuranWarna: "Besar", merk: "-", hargaEcer: 6000, hargaPack: null },
  { no: 90, namaBarang: "Lem Stick", typeUkuranWarna: "Kecil", merk: "UHU", hargaEcer: 11000, hargaPack: null },
  { no: 91, namaBarang: "Lem Tembak", typeUkuranWarna: "-", merk: "Mi - One", hargaEcer: 22000, hargaPack: null },
  { no: 92, namaBarang: "Magnetis Bookmark", typeUkuranWarna: "CX-005", merk: "-", hargaEcer: 3000, hargaPack: null },
  { no: 93, namaBarang: "Palet Lukis", typeUkuranWarna: "-", merk: "Butterfly", hargaEcer: 6000, hargaPack: null },
  { no: 94, namaBarang: "Penggaris", typeUkuranWarna: "15cm", merk: "Kayagi/No merk", hargaEcer: 2500, hargaPack: null },
  { no: 95, namaBarang: "Penggaris", typeUkuranWarna: "20cm", merk: "V-Tec", hargaEcer: 3000, hargaPack: null },
  { no: 96, namaBarang: "Penggaris", typeUkuranWarna: "30cm", merk: "Gasta dsb.", hargaEcer: 3000, hargaPack: null },
  { no: 97, namaBarang: "Penggaris", typeUkuranWarna: "30cm", merk: "Butterfly", hargaEcer: 4000, hargaPack: null },
  { no: 98, namaBarang: "Penggaris", typeUkuranWarna: "1 Set 4pcs", merk: "-", hargaEcer: 7000, hargaPack: null },
  { no: 99, namaBarang: "Penghapus", typeUkuranWarna: "Kecil", merk: "BIG dll.", hargaEcer: 2000, hargaPack: null },
  { no: 100, namaBarang: "Penghapus", typeUkuranWarna: "Besar", merk: "BIG dll.", hargaEcer: 3000, hargaPack: null },
  { no: 101, namaBarang: "Penghapus Papan", typeUkuranWarna: "-", merk: "Kenjoy", hargaEcer: 5000, hargaPack: null },
  { no: 102, namaBarang: "Pines", typeUkuranWarna: "-", merk: "ZRM", hargaEcer: 4000, hargaPack: null },
  { no: 103, namaBarang: "Pines", typeUkuranWarna: "-", merk: "A+Z", hargaEcer: 5000, hargaPack: null },
  { no: 104, namaBarang: "Pines", typeUkuranWarna: "-", merk: "Thumb Tacks", hargaEcer: 2000, hargaPack: null },
  { no: 105, namaBarang: "Rautan", typeUkuranWarna: "-", merk: "BIG", hargaEcer: 2000, hargaPack: null },
  { no: 106, namaBarang: "Rautan Duduk", typeUkuranWarna: "-", merk: "Kenko", hargaEcer: 30000, hargaPack: null },
  { no: 107, namaBarang: "Silet", typeUkuranWarna: "-", merk: "Tatra", hargaEcer: 2000, hargaPack: null },
  { no: 108, namaBarang: "Staples", typeUkuranWarna: "Kecil", merk: "Joyko", hargaEcer: 8000, hargaPack: null },
  { no: 109, namaBarang: "Staples", typeUkuranWarna: "Besar", merk: "Joyko", hargaEcer: 10000, hargaPack: null },
  { no: 110, namaBarang: "Staples", typeUkuranWarna: "-", merk: "Debozz", hargaEcer: 25000, hargaPack: null },
  { no: 111, namaBarang: "Tempat Pensil", typeUkuranWarna: "Kain Kecil", merk: "-", hargaEcer: 20000, hargaPack: null },
  { no: 112, namaBarang: "Tempat Pensil", typeUkuranWarna: "Kain Besar", merk: "-", hargaEcer: 20000, hargaPack: null },
  { no: 113, namaBarang: "Tempat Pensil", typeUkuranWarna: "Besi", merk: "-", hargaEcer: 18000, hargaPack: null },
  { no: 114, namaBarang: "Tinta Stempel", typeUkuranWarna: "Merah/Kecil", merk: "A+Z", hargaEcer: 10000, hargaPack: null },
  { no: 115, namaBarang: "Tinta Stempel", typeUkuranWarna: "Biru/Kecil", merk: "A+Z", hargaEcer: 10000, hargaPack: null },
  { no: 116, namaBarang: "Tinta Stempel", typeUkuranWarna: "Ungu/Kecil", merk: "A+Z", hargaEcer: 10000, hargaPack: null },
  { no: 117, namaBarang: "Tinta Stempel", typeUkuranWarna: "Ungu/Besar", merk: "Yamura", hargaEcer: 14000, hargaPack: null }
];